ca::mcgill::ecse211::odometer::OdometerData
volatile double ca.mcgill.ecse211.odometer.OdometerData.x
volatile double ca.mcgill.ecse211.odometer.OdometerData.y
volatile double ca.mcgill.ecse211.odometer.OdometerData.theta
volatile boolean ca.mcgill.ecse211.odometer.OdometerData.isReseting
Condition ca.mcgill.ecse211.odometer.OdometerData.doneReseting
volatile int ca.mcgill.ecse211.odometer.OdometerData.numberOfIntances
final int ca.mcgill.ecse211.odometer.OdometerData.MAX_INSTANCES
Lock ca.mcgill.ecse211.odometer.OdometerData.lock
OdometerData ca.mcgill.ecse211.odometer.OdometerData.odoData
ca.mcgill.ecse211.odometer.OdometerData.OdometerData()
Default constructor. The constructor is private. A factory is used instead such that only one instance of this class is ever created.
Referenced by ca.mcgill.ecse211.odometer.OdometerData.getOdometerData.
static synchronized OdometerData ca.mcgill.ecse211.odometer.OdometerData.getOdometerData()
OdometerData factory. Returns an OdometerData instance and makes sure that only one instance is ever created. If the user tries to instantiate multiple objects, the method throws a MultipleOdometerDataException.An OdometerData object OdometerExceptions
References ca.mcgill.ecse211.odometer.OdometerData.OdometerData.
double [] ca.mcgill.ecse211.odometer.OdometerData.getXYT()
Return the Odomometer data. Writes the current position and orientation of the robot onto the odoData array. odoData[0] = x, odoData[1] = y; odoData[2] = theta; position the array to store the odometer data the odometer data.
Referenced by ca.mcgill.ecse211.localization.UltrasonicLocalizer.localize, ca.mcgill.ecse211.odometer.Odometer.run, ca.mcgill.ecse211.odometer.OdometryCorrection.run, ca.mcgill.ecse211.odometer.OdometryCorrection.doCorrection, ca.mcgill.ecse211.project.Display.run, ca.mcgill.ecse211.project.GameUtil.findClosestPointToRobot, ca.mcgill.ecse211.project.Navigation.calculateAngleTo, ca.mcgill.ecse211.project.Navigation.travelTo, ca.mcgill.ecse211.project.Navigation.travelToWithCorrection, ca.mcgill.ecse211.project.Navigation.moveOneTileWithCorrection, ca.mcgill.ecse211.project.Navigation.turnTo, ca.mcgill.ecse211.project.Navigation.goThroughTunnel, ca.mcgill.ecse211.project.Navigation.searchRingSet.
void ca.mcgill.ecse211.odometer.OdometerData.update(double dx, double dy, double dtheta)
Adds dx, dy and dtheta to the current values of x, y and theta, respectively. Useful for odometry. dx dy dtheta
Referenced by ca.mcgill.ecse211.odometer.Odometer.run.
void ca.mcgill.ecse211.odometer.OdometerData.setXYT(double x, double y, double theta)
Overrides the values of x, y and theta. Use for odometry correction. x the value of x y the value of y theta the value of theta
Referenced by ca.mcgill.ecse211.project.Game.readData, ca.mcgill.ecse211.tests.ComponentTest.tunnelTest, ca.mcgill.ecse211.tests.ComponentTest.ringMotorTest.
void ca.mcgill.ecse211.odometer.OdometerData.setX(double x)
Overrides x. Use for odometry correction. x the value of x
Referenced by ca.mcgill.ecse211.localization.LightLocalizer.localize, ca.mcgill.ecse211.odometer.OdometryCorrection.run, ca.mcgill.ecse211.odometer.OdometryCorrection.doCorrection, ca.mcgill.ecse211.project.Navigation.travelToWithCorrection, ca.mcgill.ecse211.project.Navigation.goThroughTunnel.
void ca.mcgill.ecse211.odometer.OdometerData.setY(double y)
Overrides y. Use for odometry correction. y the value of y
Referenced by ca.mcgill.ecse211.localization.LightLocalizer.localize, ca.mcgill.ecse211.odometer.OdometryCorrection.run, ca.mcgill.ecse211.odometer.OdometryCorrection.doCorrection, ca.mcgill.ecse211.project.Navigation.travelToWithCorrection, ca.mcgill.ecse211.project.Navigation.goThroughTunnel.
void ca.mcgill.ecse211.odometer.OdometerData.setTheta(double theta)
Overrides theta. Use for odometry correction. theta the value of theta
Referenced by ca.mcgill.ecse211.localization.LightLocalizer.localize, ca.mcgill.ecse211.localization.UltrasonicLocalizer.localize, ca.mcgill.ecse211.project.Navigation.moveOneTileWithCorrection, ca.mcgill.ecse211.project.Navigation.goThroughTunnel, ca.mcgill.ecse211.project.Navigation.searchRingSet.