ca::mcgill::ecse211::project::ColorCalibrator
volatile Color ca.mcgill.ecse211.project.ColorCalibrator.currentColor
int [] ca.mcgill.ecse211.project.ColorCalibrator.colour_frequency
final int ca.mcgill.ecse211.project.ColorCalibrator.lowerYellowRBound
final int ca.mcgill.ecse211.project.ColorCalibrator.upperYellowRBound
final int ca.mcgill.ecse211.project.ColorCalibrator.lowerYellowGBound
final int ca.mcgill.ecse211.project.ColorCalibrator.upperYellowGBound
final int ca.mcgill.ecse211.project.ColorCalibrator.lowerYellowBBound
final int ca.mcgill.ecse211.project.ColorCalibrator.upperYellowBBound
final int ca.mcgill.ecse211.project.ColorCalibrator.lowerBlueRBound
final int ca.mcgill.ecse211.project.ColorCalibrator.upperBlueRBound
final int ca.mcgill.ecse211.project.ColorCalibrator.lowerBlueGBound
final int ca.mcgill.ecse211.project.ColorCalibrator.upperBlueGBound
final int ca.mcgill.ecse211.project.ColorCalibrator.lowerBlueBBound
final int ca.mcgill.ecse211.project.ColorCalibrator.upperBlueBBound
final int ca.mcgill.ecse211.project.ColorCalibrator.lowerGreenRBound
final int ca.mcgill.ecse211.project.ColorCalibrator.upperGreenRBound
final int ca.mcgill.ecse211.project.ColorCalibrator.lowerGreenGBound
final int ca.mcgill.ecse211.project.ColorCalibrator.upperGreenGBound
final int ca.mcgill.ecse211.project.ColorCalibrator.lowerGreenBBound
final int ca.mcgill.ecse211.project.ColorCalibrator.upperGreenBBound
final int ca.mcgill.ecse211.project.ColorCalibrator.lowerOrangeRBound
final int ca.mcgill.ecse211.project.ColorCalibrator.upperOrangeRBound
final int ca.mcgill.ecse211.project.ColorCalibrator.lowerOrangeGBound
final int ca.mcgill.ecse211.project.ColorCalibrator.upperOrangeGBound
final int ca.mcgill.ecse211.project.ColorCalibrator.lowerOrangeBBound
final int ca.mcgill.ecse211.project.ColorCalibrator.upperOrangeBBound
static Color ca.mcgill.ecse211.project.ColorCalibrator.getColor(int r, int g, int b)
This method returns the color of the ring currently under the light sensor r The red value to check for a ring g The green value to check for a ring b The blue value to check for a ring A Color enumeration value
Referenced by ca.mcgill.ecse211.project.Display.run, ca.mcgill.ecse211.threads.RGBPoller.runMethod.
static Color ca.mcgill.ecse211.project.ColorCalibrator.getColor()
(r >= lowerGreenRBound && r <= 5) && (b >= lowerGreenBBound && b <= upperGreenBBound) && (g <= 12 && g >= 6) GREEN This method gets the last color of the ring under the light sensorcurrent color detected by the lightSensor
static void ca.mcgill.ecse211.project.ColorCalibrator.setFrequency(Color c)
This method keeps track of how many of each colour were detected by increasing the count in the array c The Color detected by the light sensor
Referenced by ca.mcgill.ecse211.threads.RGBPoller.runMethod.
static Color ca.mcgill.ecse211.project.ColorCalibrator.getMostFrequenct()
This method returns the most frequent colour detected from multiple samplesmost frequent colour detected
References ca.mcgill.ecse211.project.ColorCalibrator.getGetColor, ca.mcgill.ecse211.project.ColorCalibrator.resetFrequency.
Referenced by ca.mcgill.ecse211.threads.RingSearcher.search.
static void ca.mcgill.ecse211.project.ColorCalibrator.resetFrequency()
This method resets the colour_frequency array to 0
Referenced by ca.mcgill.ecse211.project.ColorCalibrator.getMostFrequenct.
static Color ca.mcgill.ecse211.project.ColorCalibrator.getGetColor(int i)
Referenced by ca.mcgill.ecse211.project.ColorCalibrator.getMostFrequenct.