ca::mcgill::ecse211::project::Navigation
final int ca.mcgill.ecse211.project.Navigation.RIGHT_MOTOR_RING_COR
final int ca.mcgill.ecse211.project.Navigation.LEFT_MOTOR_RING_COR
final int ca.mcgill.ecse211.project.Navigation.FORWARD_SPEED
final int ca.mcgill.ecse211.project.Navigation.ROTATE_SPEED
final int ca.mcgill.ecse211.project.Navigation.TUNNEL_SPEED
final int ca.mcgill.ecse211.project.Navigation.TUNNEL_CORRECTION
final int ca.mcgill.ecse211.project.Navigation.Q_ACCELERATION
final int ca.mcgill.ecse211.project.Navigation.N_ACCELERATION
int ca.mcgill.ecse211.project.Navigation.leftBlackLineThre
int ca.mcgill.ecse211.project.Navigation.rightBlackLineThre
final int ca.mcgill.ecse211.project.Navigation.ZERO_DEGREE_LOW
final int ca.mcgill.ecse211.project.Navigation.ZERO_DEGREE_HIGH
final int ca.mcgill.ecse211.project.Navigation.ZERO_AFTER_LOW
final int ca.mcgill.ecse211.project.Navigation.ZERO_AFTER_HIGH
final int ca.mcgill.ecse211.project.Navigation.OTHER_ANGLE_TOLERENCE
EV3LargeRegulatedMotor ca.mcgill.ecse211.project.Navigation.leftMotor
EV3LargeRegulatedMotor ca.mcgill.ecse211.project.Navigation.rightMotor
Odometer ca.mcgill.ecse211.project.Navigation.odometer
SensorData ca.mcgill.ecse211.project.Navigation.data
ca.mcgill.ecse211.project.Navigation.Navigation(EV3LargeRegulatedMotor leftMotor, EV3LargeRegulatedMotor rightMotor)
This navigation class constructor sets up our robot to begin navigating a particular map leftMotor An EV3LargeRegularedMotor object instance that allows control of the left motor rightMotor An EV3LargeRegularedMotor object instance that allows control of the right motor
References ca.mcgill.ecse211.odometer.Odometer.getOdometer, ca.mcgill.ecse211.threads.SensorData.getSensorData.
void ca.mcgill.ecse211.project.Navigation.setSlowAcc()
This method sets the motor acceleration speed to a lower threshold value
Referenced by ca.mcgill.ecse211.localization.UltrasonicLocalizer.localize.
double ca.mcgill.ecse211.project.Navigation.calculateAngleTo(double x, double y)
This method calculates the angle necessary for the robot to rotate to face a certain point x The x coordinate of the point to face y The y coordinate of the point to face The rotation angle in degrees
References ca.mcgill.ecse211.odometer.OdometerData.getXYT.
Referenced by ca.mcgill.ecse211.project.Game.readData, ca.mcgill.ecse211.project.Navigation.travelTo, ca.mcgill.ecse211.project.Navigation.goThroughTunnel.
void ca.mcgill.ecse211.project.Navigation.travelTo(double x, double y, int speed)
This method makes our robot travel to a point by first rotating it and then traversing to the point x The x coordinate of the point to travel to y The y coordinate of the point to travel to
References ca.mcgill.ecse211.odometer.OdometerData.getXYT, ca.mcgill.ecse211.project.Navigation.calculateAngleTo, ca.mcgill.ecse211.project.Navigation.turnTo, ca.mcgill.ecse211.project.Navigation.convertDistance, ca.mcgill.ecse211.project.Game.WHEEL_RAD, ca.mcgill.ecse211.project.Game.TILE.
Referenced by ca.mcgill.ecse211.project.Game.readData, ca.mcgill.ecse211.project.Navigation.goThroughTunnel.
void ca.mcgill.ecse211.project.Navigation.travelToWithCorrection(int x, int y, boolean avoid)
This method makes the robot travel to a desired position by checking its orientation and corrects it if necessary to align with the lines on the grid. x The x coordinate to travel to y The y coordinate to travel to avoid This boolean decides if the robot will pay attention to readings from the ultrasonic sensor to avoid obstacles when navigating
References ca.mcgill.ecse211.odometer.OdometerData.getXYT, ca.mcgill.ecse211.project.GameParameters.getType, ca.mcgill.ecse211.project.GameParameters.AreaType.InStarting, ca.mcgill.ecse211.project.GameUtil.startingFinder, ca.mcgill.ecse211.project.GameUtil.searchingFinder, ca.mcgill.ecse211.project.Navigation.turnTo, ca.mcgill.ecse211.project.GameUtil.leftInstruction, ca.mcgill.ecse211.project.GameUtil.rightInstruction, ca.mcgill.ecse211.project.GameUtil.upInstruction, ca.mcgill.ecse211.project.Navigation.moveWithCorrection, ca.mcgill.ecse211.odometer.OdometerData.setX, ca.mcgill.ecse211.odometer.OdometerData.setY, ca.mcgill.ecse211.project.GameUtil.downInstruction.
Referenced by ca.mcgill.ecse211.project.Game.readData, ca.mcgill.ecse211.project.Navigation.goThroughTunnel, ca.mcgill.ecse211.tests.ComponentTest.navigationTest, ca.mcgill.ecse211.tests.ComponentTest.ringMotorTest.
synchronized void ca.mcgill.ecse211.project.Navigation.moveWithCorrection(double distance, double theta)
This method moves our robot a certain distance with corrections if required. distance The distance our robot is to travel theta The angle to be corrected to upon crossing a tile
References ca.mcgill.ecse211.project.Navigation.moveOneTileWithCorrection.
Referenced by ca.mcgill.ecse211.project.Navigation.travelToWithCorrection.
void ca.mcgill.ecse211.project.Navigation.moveOneTileWithCorrection(double theta)
This method moves the robot one tile until it detects a black line theta The angle to be corrected to upon crossing a tile
References ca.mcgill.ecse211.odometer.OdometerData.setTheta, ca.mcgill.ecse211.threads.SensorData.getL, ca.mcgill.ecse211.odometer.OdometerData.getXYT, ca.mcgill.ecse211.project.Navigation.convertDistance, ca.mcgill.ecse211.project.Game.WHEEL_RAD, ca.mcgill.ecse211.project.Game.SEN_DIS.
Referenced by ca.mcgill.ecse211.project.Navigation.moveWithCorrection, ca.mcgill.ecse211.project.Navigation.goThroughTunnel, ca.mcgill.ecse211.tests.ComponentTest.blackLineTest.
synchronized void ca.mcgill.ecse211.project.Navigation.turnTo(double angle)
This method turns our robot to a desired angle angle The angle we want our robot to turn to (in degrees)
References ca.mcgill.ecse211.odometer.OdometerData.getXYT, ca.mcgill.ecse211.project.Game.WHEEL_RAD, ca.mcgill.ecse211.project.Game.TRACK.
Referenced by ca.mcgill.ecse211.localization.LightLocalizer.localize, ca.mcgill.ecse211.localization.UltrasonicLocalizer.localize, ca.mcgill.ecse211.project.Game.readData, ca.mcgill.ecse211.project.Navigation.travelTo, ca.mcgill.ecse211.project.Navigation.travelToWithCorrection, ca.mcgill.ecse211.project.Navigation.goThroughTunnel.
void ca.mcgill.ecse211.project.Navigation.goThroughTunnel()
This method moves our robot through a tunnel by first finding the tunnel based on the lower left and upper right coordinates provided in GameParameters, aligning itself with the tunnel and then finally moving through it. the tunnel Exception
References ca.mcgill.ecse211.project.GameParameters.TN_LL, ca.mcgill.ecse211.project.GameParameters.TN_UR, ca.mcgill.ecse211.odometer.OdometerData.getXYT, ca.mcgill.ecse211.project.GameParameters.getType, ca.mcgill.ecse211.project.GameParameters.AreaType.InStarting, ca.mcgill.ecse211.project.GameParameters.AreaType.Searching, ca.mcgill.ecse211.project.GameUtil.average, ca.mcgill.ecse211.project.Navigation.calculateAngleTo, ca.mcgill.ecse211.project.Navigation.turnTo, ca.mcgill.ecse211.project.Navigation.forward, ca.mcgill.ecse211.project.Navigation.turn, ca.mcgill.ecse211.odometer.OdometerData.setTheta, ca.mcgill.ecse211.project.Navigation.moveOneTileWithCorrection, ca.mcgill.ecse211.odometer.OdometerData.setX, ca.mcgill.ecse211.odometer.OdometerData.setY, ca.mcgill.ecse211.project.GameUtil.isSafe, ca.mcgill.ecse211.project.Navigation.travelToWithCorrection, ca.mcgill.ecse211.project.Navigation.travelTo.
Referenced by ca.mcgill.ecse211.project.Game.readData, ca.mcgill.ecse211.tests.ComponentTest.tunnelTest.
void ca.mcgill.ecse211.project.Navigation.searchRingSet(RingSearcher searcher, boolean correct, boolean reset)
This method moves our robot towards a ring set by noting ultrasonic sensor readings searcher A RingSearcher object instance to detect ring colors and navigate around a ring set correct A boolean that decides whether to correct our position when searching for a ring reset A boolean that decides whether to rotate the rod motor to its original position
References ca.mcgill.ecse211.odometer.OdometerData.getXYT, ca.mcgill.ecse211.project.RingSearcher.prepareRetrieve, ca.mcgill.ecse211.project.RingSearcher.search, ca.mcgill.ecse211.project.Navigation.forward, ca.mcgill.ecse211.project.Game.TILE, ca.mcgill.ecse211.project.RingSearcher.detectColor, ca.mcgill.ecse211.project.RingSearcher.finishSearch, ca.mcgill.ecse211.project.RingSearcher.safeRod, ca.mcgill.ecse211.project.RingSearcher.retrieveRing.
Referenced by ca.mcgill.ecse211.project.Game.readData, ca.mcgill.ecse211.tests.ComponentTest.ringMotorTest.
void ca.mcgill.ecse211.project.Navigation.turn(int angle)
This method rotates the robot by a certain angle angle The angle (in degrees) to rotate our robot to
References ca.mcgill.ecse211.project.Game.WHEEL_RAD, ca.mcgill.ecse211.project.Game.TRACK.
Referenced by ca.mcgill.ecse211.localization.UltrasonicLocalizer.localize, ca.mcgill.ecse211.project.Navigation.goThroughTunnel, ca.mcgill.ecse211.tests.ComponentTest.ringMotorTest, ca.mcgill.ecse211.tests.ComponentTest.blackLineTest.
void ca.mcgill.ecse211.project.Navigation.forward(int speed, double distance)
This method moves our robot forward speed An integer that denotes the speed to rotate our wheels at distance A double that denotes the distance to travel
References ca.mcgill.ecse211.project.Navigation.convertDistance, ca.mcgill.ecse211.project.Game.WHEEL_RAD, ca.mcgill.ecse211.project.Game.TILE.
Referenced by ca.mcgill.ecse211.project.Navigation.goThroughTunnel, ca.mcgill.ecse211.project.Navigation.searchRingSet.
void ca.mcgill.ecse211.project.Navigation.stop()
This method stops both motors
int ca.mcgill.ecse211.project.Navigation.charToRotation(char direction)
This method converts directions our robot can face (up, down, right, left) into degrees direction The direction to convert The angle the robot should face in degrees
synchronized void ca.mcgill.ecse211.project.Navigation.moveBackWithCorrection()
This method moves the robot backwards until a black line is detected
void ca.mcgill.ecse211.project.Navigation.moveUntilLineDetection(boolean checkForBlackLine)
This method moves the robot until a black line has been detected checkForBlackLine This boolean decides whether to check for a black line.
void ca.mcgill.ecse211.project.Navigation.travelToTunnelEntrance(ArrayList< int[]> points, int n, int multiplier)
This method navigates our robot to the entrance of a tunnel points An ArrayList of points to navigate our robot to the tunnel entrance n An integer index to modify the list of points at multiplier An integer to add onto each point
static int ca.mcgill.ecse211.project.Navigation.convertDistance(double radius, double distance)
This method converts a distance to the total number of wheel rotations needed to cover that distance. radius The radius of our wheels distance The distance to travel A number of wheel rotations
Referenced by ca.mcgill.ecse211.localization.LightLocalizer.localize, ca.mcgill.ecse211.project.Navigation.travelTo, ca.mcgill.ecse211.project.Navigation.moveOneTileWithCorrection, ca.mcgill.ecse211.project.Navigation.forward.
static int ca.mcgill.ecse211.project.Navigation.convertAngle(double radius, double width, double angle)
This method converts an angle value to the number of wheel rotations needed to achieve rotation radius The radius of our wheels width The width angle The angle to convert A number of wheel rotations