ca::mcgill::ecse211::threads::RingSearcher
final int ca.mcgill.ecse211.threads.RingSearcher.ACCELERATION
EV3LargeRegulatedMotor ca.mcgill.ecse211.threads.RingSearcher.sensorMotor
EV3LargeRegulatedMotor ca.mcgill.ecse211.threads.RingSearcher.rodMotor
boolean ca.mcgill.ecse211.threads.RingSearcher.started
Odometer ca.mcgill.ecse211.threads.RingSearcher.odometer
SensorData ca.mcgill.ecse211.threads.RingSearcher.data
ca.mcgill.ecse211.threads.RingSearcher.RingSearcher(EV3LargeRegulatedMotor sensorMotor, EV3LargeRegulatedMotor rodMotor)
This class provides method to check if there is a ring and if the ring is the color we want storagenMotor the motor to move the storage of the robot rodMotor the motor for the rod to collect the ring OdometerExceptions
References ca.mcgill.ecse211.odometer.Odometer.getOdometer, ca.mcgill.ecse211.threads.SensorData.getSensorData.
void ca.mcgill.ecse211.threads.RingSearcher.search()
This method searches for the ring and identify its color based using the rod, It will beep based on the color of the ring
References ca.mcgill.ecse211.project.Game.INSTANCE, ca.mcgill.ecse211.project.ColorCalibrator.getMostFrequenct.
Referenced by ca.mcgill.ecse211.project.Navigation.searchRingSet.
void ca.mcgill.ecse211.threads.RingSearcher.prepareRetrieve()
This method rotate the rod to a suitable position for retrieve the ring
Referenced by ca.mcgill.ecse211.project.Navigation.searchRingSet.
void ca.mcgill.ecse211.threads.RingSearcher.retrieveRing()
this method retrieve the searched ring
Referenced by ca.mcgill.ecse211.project.Navigation.searchRingSet.
void ca.mcgill.ecse211.threads.RingSearcher.resetRodMotor()
Rotate the rod back to the original position
Referenced by ca.mcgill.ecse211.project.Navigation.searchRingSet.
void ca.mcgill.ecse211.threads.RingSearcher.protectRing()
Protect the ring from dropping
Referenced by ca.mcgill.ecse211.project.Game.readData.
void ca.mcgill.ecse211.threads.RingSearcher.unloadRing()
unload all rings
Referenced by ca.mcgill.ecse211.project.Game.readData.