ca::mcgill::ecse211::threads::SensorData
double [] ca.mcgill.ecse211.threads.SensorData.lights
volatile double ca.mcgill.ecse211.threads.SensorData.distance
volatile double ca.mcgill.ecse211.threads.SensorData.angle
int ca.mcgill.ecse211.threads.SensorData.rgb[][]
volatile int ca.mcgill.ecse211.threads.SensorData.numberOfIntances
final int ca.mcgill.ecse211.threads.SensorData.MAX_INSTANCES
Lock ca.mcgill.ecse211.threads.SensorData.lightLock
Lock ca.mcgill.ecse211.threads.SensorData.rgbLock
SensorData ca.mcgill.ecse211.threads.SensorData.sensorData
ca.mcgill.ecse211.threads.SensorData.SensorData()
Default constructor. The constructor is private. A factory is used instead such that only one instance of this class is ever created.
Referenced by ca.mcgill.ecse211.threads.SensorData.getSensorData.
static synchronized SensorData ca.mcgill.ecse211.threads.SensorData.getSensorData()
OdometerData factory. Returns an OdometerData instance and makes sure that only one instance is ever created. If the user tries to instantiate multiple objects, the method throws a MultipleOdometerDataException.An OdometerData object OdometerExceptions
References ca.mcgill.ecse211.threads.SensorData.SensorData.
Referenced by ca.mcgill.ecse211.localization.LightLocalizer.LightLocalizer, ca.mcgill.ecse211.localization.UltrasonicLocalizer.UltrasonicLocalizer, ca.mcgill.ecse211.project.Display.Display, ca.mcgill.ecse211.project.Game.preparation, ca.mcgill.ecse211.project.Navigation.Navigation, ca.mcgill.ecse211.threads.RingSearcher.RingSearcher.
double ca.mcgill.ecse211.threads.SensorData.getD()
Return the ultraSonic distance data.the sensor data.
Referenced by ca.mcgill.ecse211.localization.UltrasonicLocalizer.localize.
double [] ca.mcgill.ecse211.threads.SensorData.getL()
get the light value data from the two light sensors (protected by lightLock) : data from light sensor
Referenced by ca.mcgill.ecse211.localization.LightLocalizer.localize, ca.mcgill.ecse211.project.Navigation.moveWithCorrection.
int [] ca.mcgill.ecse211.threads.SensorData.getRGB()
get the rgb data for light sensor (protected by rgb lock): rgb data
Referenced by ca.mcgill.ecse211.project.Display.run.
double ca.mcgill.ecse211.threads.SensorData.getA()
(deprecated, not using) This method returns the currently stored angle value from the gyro sensorThe current angle value
Referenced by ca.mcgill.ecse211.project.Display.run.
void ca.mcgill.ecse211.threads.SensorData.setD(double d)
This method overwrites the distance value. Use for ultrasonic sensor. d The value to overwrite distance with
Referenced by ca.mcgill.ecse211.threads.UltrasonicPoller.runMethod.
void ca.mcgill.ecse211.threads.SensorData.setA(double a)
(deprecated not usings) This method overwrites the angle value. a The value to overwrite angle with
void ca.mcgill.ecse211.threads.SensorData.setRGB(int r, int g, int b)
set rgb data for color sensor (protected by rgb lock) r red value g green value b blue value
Referenced by ca.mcgill.ecse211.threads.RGBPoller.runMethod.
void ca.mcgill.ecse211.threads.SensorData.setL(double l[])
This method overwrites the light value. (protected by light lock) l The value to overwrite the current light value with
Referenced by ca.mcgill.ecse211.threads.LightPoller.runMethod.