ca::mcgill::ecse211::project::Game
ThreadControl ca.mcgill.ecse211.project.Game.rgbPoller
ThreadControl ca.mcgill.ecse211.project.Game.lightPoller
ThreadControl ca.mcgill.ecse211.project.Game.motorControlThread
ThreadControl ca.mcgill.ecse211.project.Game.usPoller
boolean ca.mcgill.ecse211.project.Game.hasReadData
final EV3LargeRegulatedMotor ca.mcgill.ecse211.project.Game.leftMotor
Motor object instance that allows control of the left motor connected to port A
Referenced by ca.mcgill.ecse211.tests.ComponentTest.navigationTest.
final EV3LargeRegulatedMotor ca.mcgill.ecse211.project.Game.rightMotor
Motor object instance that allows control of the right motor connected to port D
Referenced by ca.mcgill.ecse211.tests.ComponentTest.navigationTest.
final EV3LargeRegulatedMotor ca.mcgill.ecse211.project.Game.storageMotor
Motor object instance that allows control of the motor on storage rod
Referenced by ca.mcgill.ecse211.tests.ComponentTest.RingMotorTest.
final EV3MediumRegulatedMotor ca.mcgill.ecse211.project.Game.rodMotor
Motor object instance taht allows control of the motor on the rod for collecting rings
Referenced by ca.mcgill.ecse211.tests.ComponentTest.RingMotorTest.
final double ca.mcgill.ecse211.project.Game.TILE
length of the tile
Referenced by ca.mcgill.ecse211.odometer.Odometer.run, ca.mcgill.ecse211.odometer.OdometryCorrection.doCorrection, ca.mcgill.ecse211.project.Navigation.moveWithCorrection.
final double ca.mcgill.ecse211.project.Game.WHEEL_RAD
This variable denotes the radius of our wheels in cm.
Referenced by ca.mcgill.ecse211.localization.LightLocalizer.localize, ca.mcgill.ecse211.project.Navigation.moveWithCorrection, ca.mcgill.ecse211.project.Navigation.turnTo, ca.mcgill.ecse211.project.Navigation.rotate.
final double ca.mcgill.ecse211.project.Game.TRACK
This variable denotes the track distance between the center of the wheels in cm (measured and adjusted based on trial and error).
Referenced by ca.mcgill.ecse211.project.Navigation.turnTo, ca.mcgill.ecse211.project.Navigation.rotate.
final double ca.mcgill.ecse211.project.Game.SEN_DIS
The distance between light sensor and the center of the robot in cm
Referenced by ca.mcgill.ecse211.project.Navigation.moveWithCorrection.
static void ca.mcgill.ecse211.project.Game.preparation()
Prepare for the game: starting thread, read all arguments OdometerExceptions
References ca.mcgill.ecse211.odometer.Odometer.getOdometer, ca.mcgill.ecse211.threads.SensorData.getSensorData.
Referenced by ca.mcgill.ecse211.project.Main.main.
static synchronized void ca.mcgill.ecse211.project.Game.readData()
Read data from the wifi class (using another thread)
Referenced by ca.mcgill.ecse211.project.Game.runGame.
static synchronized void ca.mcgill.ecse211.project.Game.runGame()
This method contains main logic for the game plays OdometerExceptions
References ca.mcgill.ecse211.project.Game.readData, ca.mcgill.ecse211.localization.UltrasonicLocalizer.localize, ca.mcgill.ecse211.localization.LightLocalizer.localize, ca.mcgill.ecse211.project.GameParameters.SC.
Referenced by ca.mcgill.ecse211.project.Main.main.