ca::mcgill::ecse211::project::RingSearcher
final int ca.mcgill.ecse211.project.RingSearcher.ROD_RETRIEVE
final int ca.mcgill.ecse211.project.RingSearcher.ROD_PREPARE
final int ca.mcgill.ecse211.project.RingSearcher.SENSOR_ROTATION
final int ca.mcgill.ecse211.project.RingSearcher.ACCELERATION
final int ca.mcgill.ecse211.project.RingSearcher.ROD_SPEED
final int ca.mcgill.ecse211.project.RingSearcher.SENSOR_SPEED
EV3LargeRegulatedMotor ca.mcgill.ecse211.project.RingSearcher.sensorMotor
EV3LargeRegulatedMotor ca.mcgill.ecse211.project.RingSearcher.rodMotor
boolean ca.mcgill.ecse211.project.RingSearcher.started
Odometer ca.mcgill.ecse211.project.RingSearcher.odometer
SensorData ca.mcgill.ecse211.project.RingSearcher.data
ca.mcgill.ecse211.project.RingSearcher.RingSearcher(EV3LargeRegulatedMotor sensorMotor, EV3LargeRegulatedMotor rodMotor)
This RingSearcher class constructor checks if there is a ring to collect and records its color sensorMotor An EV3LargeRegulatedMotor object instance that controls a sensor motor rodMotor An EV3LargeRegulatedMotor object instance that controls the rod with a light sensor for ring color detection OdometerExceptions
References ca.mcgill.ecse211.odometer.Odometer.getOdometer, ca.mcgill.ecse211.threads.SensorData.getSensorData.
void ca.mcgill.ecse211.project.RingSearcher.search(int angle)
This method searches for a ring and rotates the sensorMotor rod angle An integer to rotate the motor for the sensor to
Referenced by ca.mcgill.ecse211.project.Navigation.searchRingSet.
void ca.mcgill.ecse211.project.RingSearcher.detectColor()
This method causes our robot to beep a certain number of times to identify what ring it is picking up
References ca.mcgill.ecse211.project.Game.INSTANCE, ca.mcgill.ecse211.project.ColorCalibrator.getMostFrequenct.
Referenced by ca.mcgill.ecse211.project.Navigation.searchRingSet.
void ca.mcgill.ecse211.project.RingSearcher.prepareSearch()
This method prepares our robot to search for a ring
Referenced by ca.mcgill.ecse211.project.Game.readData.
void ca.mcgill.ecse211.project.RingSearcher.finishSearch()
This method indicates that our robot is done searching for a ring
Referenced by ca.mcgill.ecse211.project.Navigation.searchRingSet.
void ca.mcgill.ecse211.project.RingSearcher.resetSearch()
This method retracts our ring searching rod
Referenced by ca.mcgill.ecse211.project.Game.readData.
void ca.mcgill.ecse211.project.RingSearcher.prepareRetrieve()
This method rotates the rod to a suitable position to allow a ring to be picked up
Referenced by ca.mcgill.ecse211.project.Navigation.searchRingSet.
void ca.mcgill.ecse211.project.RingSearcher.retrieveRing()
This method rotates the rod to be ready to retrieve a ring
Referenced by ca.mcgill.ecse211.project.Navigation.searchRingSet.
void ca.mcgill.ecse211.project.RingSearcher.safeRod()
This method rotates the rod to a safe position
Referenced by ca.mcgill.ecse211.project.Navigation.searchRingSet.
void ca.mcgill.ecse211.project.RingSearcher.resetRodMotor()
This method rotates the rod back to its original position