ca::mcgill::ecse211::project::GameUtil
PathFinder ca.mcgill.ecse211.project.GameUtil.startingFinder
This variable stores a PathFinder object instance that helps to create a path to navigate at the start of a competition.
Referenced by ca.mcgill.ecse211.project.Game.runGame, ca.mcgill.ecse211.project.Navigation.travelToWithCorrection, ca.mcgill.ecse211.tests.ComponentTest.tunnelTest, ca.mcgill.ecse211.tests.ComponentTest.ringMotorTest, ca.mcgill.ecse211.tests.ComponentTest.blackLineTest.
PathFinder ca.mcgill.ecse211.project.GameUtil.searchingFinder
This variable stores a PathFinder object instance that helps to create a path to navigate during the searching phase of a competition.
Referenced by ca.mcgill.ecse211.project.Game.runGame, ca.mcgill.ecse211.project.Navigation.travelToWithCorrection, ca.mcgill.ecse211.tests.ComponentTest.tunnelTest, ca.mcgill.ecse211.tests.ComponentTest.ringMotorTest, ca.mcgill.ecse211.tests.ComponentTest.blackLineTest.
char ca.mcgill.ecse211.project.GameUtil.leftInstruction
This variable stores a character denoting a left turn is required.
Referenced by ca.mcgill.ecse211.project.Navigation.travelToWithCorrection.
char ca.mcgill.ecse211.project.GameUtil.rightInstruction
This variable stores a character denoting a right turn is required.
Referenced by ca.mcgill.ecse211.project.Navigation.travelToWithCorrection.
char ca.mcgill.ecse211.project.GameUtil.upInstruction
This variable stores a character denoting that we need to navigate upwards.
Referenced by ca.mcgill.ecse211.project.Navigation.travelToWithCorrection.
char ca.mcgill.ecse211.project.GameUtil.downInstruction
This variable stores a character denoting that we need to navigate downwards.
Referenced by ca.mcgill.ecse211.project.Navigation.travelToWithCorrection.
static boolean ca.mcgill.ecse211.project.GameUtil.isSafe(int[] coor)
This method checks if a coordinate pair is safe to travel to (i.e. it is not a wall, tree or inside a tunnel) coor An array with a pair of coordinates A boolean that is true if safe, false otherwise
References ca.mcgill.ecse211.project.GameParameters.TN_LL, ca.mcgill.ecse211.project.GameParameters.TN_UR, ca.mcgill.ecse211.project.GameParameters.TREE_US, ca.mcgill.ecse211.project.GameParameters.Grid_UR.
Referenced by ca.mcgill.ecse211.project.Game.readData, ca.mcgill.ecse211.project.Navigation.goThroughTunnel.
static double [] ca.mcgill.ecse211.project.GameUtil.average(int[] p1, int[] p2)
This method finds the mid point between two coordinate pairs p1 The first pair of coordinates p2 The second pair of coordinates An array with the mid point coordinates
Referenced by ca.mcgill.ecse211.project.Navigation.goThroughTunnel.
static double ca.mcgill.ecse211.project.GameUtil.distanceFrom(int x, int y, double[] position)
This method finds the distance from some starting coordinates to a target pair of coordinates x The target x coordinate y The target y coordinate position The starting pair of coordinates The distance from the starting position to the target coordinates
Referenced by ca.mcgill.ecse211.project.GameUtil.findClosestPointToRobot.
static int ca.mcgill.ecse211.project.GameUtil.findClosestPointToRobot(int[][] points)
This method finds the closest point to our robot's current position from a set of points points A two dimensional array of points An index that represents the closest point to our robot
References ca.mcgill.ecse211.odometer.Odometer.getOdometer, ca.mcgill.ecse211.odometer.OdometerData.getXYT, ca.mcgill.ecse211.project.GameUtil.distanceFrom.
Referenced by ca.mcgill.ecse211.project.Game.readData.
static boolean ca.mcgill.ecse211.project.GameUtil.isIslandBoundary(int[] coor)
This method checks if a given point is on an island boundary coor An array with a pair of coordinates to check A boolean that represents whether the given point is on the boundary of an island
References ca.mcgill.ecse211.project.GameParameters.Island_LL, ca.mcgill.ecse211.project.GameParameters.Island_UR.
Referenced by ca.mcgill.ecse211.project.Game.readData.
static void ca.mcgill.ecse211.project.GameUtil.playMusic()
This method plays music
Referenced by ca.mcgill.ecse211.project.Game.readData, ca.mcgill.ecse211.tests.ComponentTest.musicTest.