ca::mcgill::ecse211::threads::ThreadControl
int ca.mcgill.ecse211.threads.ThreadControl.WAIT_TIME
Referenced by ca.mcgill.ecse211.threads.LightPoller.LightPoller, ca.mcgill.ecse211.threads.UltrasonicPoller.UltrasonicPoller.
boolean ca.mcgill.ecse211.threads.ThreadControl.isStarted
Object ca.mcgill.ecse211.threads.ThreadControl.lockObject
Referenced by ca.mcgill.ecse211.threads.ThreadControl.waitForThisThread, ca.mcgill.ecse211.threads.ThreadControl.shouldWait, ca.mcgill.ecse211.threads.ThreadControl.setWait.
boolean ca.mcgill.ecse211.threads.ThreadControl.shouldWait
synchronized void ca.mcgill.ecse211.threads.ThreadControl.run()
This method implements the functionality to run a thread
References ca.mcgill.ecse211.threads.ThreadControl.runMethod.
synchronized boolean ca.mcgill.ecse211.threads.ThreadControl.isStarted()
This method checks if this thread has been previously startedA boolean denoting true if the thread is running, false otherwise
Referenced by ca.mcgill.ecse211.threads.LightPoller.LightPoller, ca.mcgill.ecse211.threads.RGBPoller.RGBPoller, ca.mcgill.ecse211.threads.UltrasonicPoller.UltrasonicPoller.
synchronized void ca.mcgill.ecse211.threads.ThreadControl.setStart(boolean start)
This method starts a paused thread start A boolean to set the current thread status
Referenced by ca.mcgill.ecse211.project.Game.readData.
void ca.mcgill.ecse211.threads.ThreadControl.waitForThisThread()
This method waits for this thread to finish
References ca.mcgill.ecse211.threads.ThreadControl.lockObject.
boolean ca.mcgill.ecse211.threads.ThreadControl.shouldWait()
This method returns the variable shouldWaitA boolean variable called shouldWait
References ca.mcgill.ecse211.threads.ThreadControl.lockObject.
Referenced by ca.mcgill.ecse211.threads.ThreadControl.setWait.
void ca.mcgill.ecse211.threads.ThreadControl.setWait(boolean shouldWait)
This method sets the variable shouldWait for this thread shouldWait A boolean variable to decide whether other threads should wait for this thread
References ca.mcgill.ecse211.threads.ThreadControl.lockObject, ca.mcgill.ecse211.threads.ThreadControl.shouldWait, ca.mcgill.ecse211.threads.ThreadControl.runMethod.
abstract void ca.mcgill.ecse211.threads.ThreadControl.runMethod()
Referenced by ca.mcgill.ecse211.threads.ThreadControl.run, ca.mcgill.ecse211.threads.ThreadControl.setWait.