ca::mcgill::ecse211::tests::ComponentTest
static void ca.mcgill.ecse211.tests.ComponentTest.runTest(Type testType)
This method executes a specific type of tests type The type of tests to execute Exception
References ca.mcgill.ecse211.tests.ComponentTest.navigationTest, ca.mcgill.ecse211.tests.ComponentTest.localizationTest, ca.mcgill.ecse211.tests.ComponentTest.ultrasonicSensorTest, ca.mcgill.ecse211.tests.ComponentTest.lightSensorTest, ca.mcgill.ecse211.tests.ComponentTest.ringMotorTest.
static void ca.mcgill.ecse211.tests.ComponentTest.navigationTest()
This method runs Navigation tests OdometerExceptions
References ca.mcgill.ecse211.project.Game.leftMotor, ca.mcgill.ecse211.project.Game.rightMotor, ca.mcgill.ecse211.project.Navigation.travelToWithCorrection.
Referenced by ca.mcgill.ecse211.project.Main.main, ca.mcgill.ecse211.tests.ComponentTest.runTest.
static void ca.mcgill.ecse211.tests.ComponentTest.tunnelTest()
This method runs Tunnel tests Exception
References ca.mcgill.ecse211.project.Game.leftMotor, ca.mcgill.ecse211.project.Game.rightMotor, ca.mcgill.ecse211.project.GameUtil.searchingFinder, ca.mcgill.ecse211.project.GameParameters.Island_LL, ca.mcgill.ecse211.project.GameParameters.Island_UR, ca.mcgill.ecse211.project.GameUtil.startingFinder, ca.mcgill.ecse211.project.GameParameters.US_LL, ca.mcgill.ecse211.project.GameParameters.US_UR, ca.mcgill.ecse211.odometer.Odometer.getOdometer, ca.mcgill.ecse211.odometer.OdometerData.setXYT, ca.mcgill.ecse211.project.Navigation.goThroughTunnel.
static void ca.mcgill.ecse211.tests.ComponentTest.localizationTest()
This method runs Localization tests Exception
References ca.mcgill.ecse211.project.Game.leftMotor, ca.mcgill.ecse211.project.Game.rightMotor, ca.mcgill.ecse211.localization.UltrasonicLocalizer.localize, ca.mcgill.ecse211.localization.LightLocalizer.localize, ca.mcgill.ecse211.project.GameParameters.SC.
Referenced by ca.mcgill.ecse211.tests.ComponentTest.runTest.
static void ca.mcgill.ecse211.tests.ComponentTest.ultrasonicSensorTest()
This method runs UltrasonicSensor tests Exception
Referenced by ca.mcgill.ecse211.tests.ComponentTest.runTest.
static void ca.mcgill.ecse211.tests.ComponentTest.lightSensorTest()
This method runs LightSensor tests Exception
Referenced by ca.mcgill.ecse211.tests.ComponentTest.runTest.
static void ca.mcgill.ecse211.tests.ComponentTest.ringMotorTest()
This method runs RingDetection tests Exception
References ca.mcgill.ecse211.project.Game.INSTANCE, ca.mcgill.ecse211.project.Game.sensorMotor, ca.mcgill.ecse211.project.Game.rodMotor, ca.mcgill.ecse211.project.Game.leftMotor, ca.mcgill.ecse211.project.Game.rightMotor, ca.mcgill.ecse211.project.GameUtil.searchingFinder, ca.mcgill.ecse211.project.GameParameters.Island_LL, ca.mcgill.ecse211.project.GameParameters.Island_UR, ca.mcgill.ecse211.project.GameUtil.startingFinder, ca.mcgill.ecse211.project.GameParameters.US_LL, ca.mcgill.ecse211.project.GameParameters.US_UR, ca.mcgill.ecse211.odometer.Odometer.getOdometer, ca.mcgill.ecse211.odometer.OdometerData.setXYT, ca.mcgill.ecse211.project.Navigation.travelToWithCorrection, ca.mcgill.ecse211.project.Navigation.turn, ca.mcgill.ecse211.project.Navigation.searchRingSet.
Referenced by ca.mcgill.ecse211.tests.ComponentTest.runTest.
static void ca.mcgill.ecse211.tests.ComponentTest.blackLineTest()
This method tests black line detection Exception
References ca.mcgill.ecse211.project.Game.leftMotor, ca.mcgill.ecse211.project.Game.rightMotor, ca.mcgill.ecse211.project.GameUtil.searchingFinder, ca.mcgill.ecse211.project.GameParameters.Island_LL, ca.mcgill.ecse211.project.GameParameters.Island_UR, ca.mcgill.ecse211.project.GameUtil.startingFinder, ca.mcgill.ecse211.project.Navigation.moveOneTileWithCorrection, ca.mcgill.ecse211.project.Navigation.turn.
static void ca.mcgill.ecse211.tests.ComponentTest.musicTest()
This method tests that music can be played Exception
References ca.mcgill.ecse211.project.GameUtil.playMusic.