ca::mcgill::ecse211::project::Game
Status ca.mcgill.ecse211.project.Game.status
ThreadControl ca.mcgill.ecse211.project.Game.rgbPoller
ThreadControl ca.mcgill.ecse211.project.Game.lightPoller
ThreadControl ca.mcgill.ecse211.project.Game.motorControlThread
ThreadControl ca.mcgill.ecse211.project.Game.usPoller
boolean ca.mcgill.ecse211.project.Game.hasReadData
static final EV3LargeRegulatedMotor ca.mcgill.ecse211.project.Game.leftMotor
Motor object instance that allows control of the left motor connected to port A
Referenced by ca.mcgill.ecse211.tests.ComponentTest.navigationTest.
static final EV3LargeRegulatedMotor ca.mcgill.ecse211.project.Game.rightMotor
Motor object instance that allows control of the right motor connected to port D
Referenced by ca.mcgill.ecse211.tests.ComponentTest.navigationTest.
static final EV3LargeRegulatedMotor ca.mcgill.ecse211.project.Game.storageMotor
Motor object instance that allows control of the motor on storage rod
Referenced by ca.mcgill.ecse211.tests.ComponentTest.ringMotorTest.
static final EV3MediumRegulatedMotor ca.mcgill.ecse211.project.Game.rodMotor
Motor object instance taht allows control of the motor on the rod for collecting rings
Referenced by ca.mcgill.ecse211.tests.ComponentTest.ringMotorTest.
static final double ca.mcgill.ecse211.project.Game.TILE
length of the tile
Referenced by ca.mcgill.ecse211.odometer.Odometer.run, ca.mcgill.ecse211.odometer.OdometryCorrection.doCorrection, ca.mcgill.ecse211.project.Navigation.moveWithCorrection.
static final double ca.mcgill.ecse211.project.Game.WHEEL_RAD
This variable denotes the radius of our wheels in cm.
Referenced by ca.mcgill.ecse211.localization.LightLocalizer.localize, ca.mcgill.ecse211.project.Navigation.moveWithCorrection, ca.mcgill.ecse211.project.Navigation.turnTo, ca.mcgill.ecse211.project.Navigation.rotate.
static final double ca.mcgill.ecse211.project.Game.TRACK
This variable denotes the track distance between the center of the wheels in cm (measured and adjusted based on trial and error).
Referenced by ca.mcgill.ecse211.project.Navigation.turnTo, ca.mcgill.ecse211.project.Navigation.rotate.
static final double ca.mcgill.ecse211.project.Game.SEN_DIS
The distance between light sensor and the center of the robot in cm
Referenced by ca.mcgill.ecse211.project.Navigation.moveWithCorrection.
String ca.mcgill.ecse211.project.Game.getStatusFullName()
get the full name of the status
Status ca.mcgill.ecse211.project.Game.getStatus()
get the current status of the game
boolean ca.mcgill.ecse211.project.Game.ready()
perform the localization and go to navigation
References ca.mcgill.ecse211.project.Game.Status.Localization.
boolean ca.mcgill.ecse211.project.Game.localized()
Navigating to the tunnel and to the search areawhether transition successful
References ca.mcgill.ecse211.project.Game.Status.NavigationSafe.
boolean ca.mcgill.ecse211.project.Game.navigatedToTunnel()
whether transition successfulwhether transition successful
References ca.mcgill.ecse211.project.Game.Status.NavigationSearch, ca.mcgill.ecse211.project.Game.Status.NavigationSafe.
boolean ca.mcgill.ecse211.project.Game.navigatedToStart()
Navigate to the starting cornerwhether transition successful
References ca.mcgill.ecse211.project.Game.Status.Idle.
boolean ca.mcgill.ecse211.project.Game.navigatedToTree()
Navigate to the tree and try find the ringswhether transition successful
References ca.mcgill.ecse211.project.Game.Status.RingSearch.
boolean ca.mcgill.ecse211.project.Game.ringFound()
if ring found, get the ringwhether transition successful
References ca.mcgill.ecse211.project.Game.Status.NavigationSearch.
boolean ca.mcgill.ecse211.project.Game.ringNotFound()
In case if the ring is not foundwhether transition successful
References ca.mcgill.ecse211.project.Game.Status.NavigationSearch.
void ca.mcgill.ecse211.project.Game.preparation()
Prepare for the game: starting thread, read all arguments OdometerExceptions
References ca.mcgill.ecse211.odometer.Odometer.getOdometer, ca.mcgill.ecse211.threads.SensorData.getSensorData.
Referenced by ca.mcgill.ecse211.project.Main.main.
synchronized void ca.mcgill.ecse211.project.Game.readData()
Read data from the wifi class (using another thread)
synchronized void ca.mcgill.ecse211.project.Game.runGame()
This method contains main logic for the game plays OdometerExceptions
References ca.mcgill.ecse211.localization.UltrasonicLocalizer.localize, ca.mcgill.ecse211.localization.LightLocalizer.localize, ca.mcgill.ecse211.project.GameParameters.SC.
Referenced by ca.mcgill.ecse211.project.Main.main.
void ca.mcgill.ecse211.project.Game.setStatus(Status aStatus)
set the current status aStatus current status to set
static Game ca.mcgill.ecse211.project.Game.getGame()
Referenced by ca.mcgill.ecse211.project.Main.main.