.TH "ca.mcgill.ecse211.project.Main" 3 "Thu Oct 25 2018" "Version 1.0" "ECSE211 - Fall 2018 - Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.project.Main
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static boolean \fBtest\fP = false"
.br
.ti -1c
.RI "static ComponentTest\&.Type \fBcType\fP = ComponentTest\&.Type\&.LightSensor"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class implements the main starting point for the Search and Localize lab
.PP
\fBAuthor:\fP
.RS 4
Caspar Cedro 
.PP
Percy Chen 
.PP
Patrick Erath 
.PP
Anssam Ghezala 
.PP
Susan Matuszewski 
.PP
Kamy Moussavi Kafi 
.RE
.PP

.PP
Definition at line 35 of file Main\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ca\&.mcgill\&.ecse211\&.project\&.Main\&.main (String [] args)\fC [static]\fP"
This method is our main entry point - instantiate objects used and set up sensor\&.
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP an array of arguments that can be passed in via commandline or otherwise\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 52 of file Main\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "ComponentTest\&.Type ca\&.mcgill\&.ecse211\&.project\&.Main\&.cType = ComponentTest\&.Type\&.LightSensor\fC [static]\fP"
Type of test 
.PP
Definition at line 44 of file Main\&.java\&.
.SS "boolean ca\&.mcgill\&.ecse211\&.project\&.Main\&.test = false\fC [static]\fP"
Whether Enable test 
.PP
Definition at line 39 of file Main\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Final Project from the source code\&.
