.TH "ca.mcgill.ecse211.tests.ComponentTest.Type" 3 "Thu Nov 8 2018" "Version 1.0" "ECSE211 - Fall 2018 - Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.tests.ComponentTest.Type
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNavigation\fP"
.br
.ti -1c
.RI "\fBLocalization\fP"
.br
.ti -1c
.RI "\fBUltrasonicSensor\fP"
.br
.ti -1c
.RI "\fBLightSensor\fP"
.br
.ti -1c
.RI "\fBRingDetection\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file ComponentTest\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.Type\&.LightSensor"

.PP
Definition at line 29 of file ComponentTest\&.java\&.
.SS "ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.Type\&.Localization"

.PP
Definition at line 29 of file ComponentTest\&.java\&.
.SS "ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.Type\&.Navigation"

.PP
Definition at line 29 of file ComponentTest\&.java\&.
.SS "ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.Type\&.RingDetection"

.PP
Definition at line 29 of file ComponentTest\&.java\&.
.SS "ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.Type\&.UltrasonicSensor"

.PP
Definition at line 29 of file ComponentTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Final Project from the source code\&.
