.TH "ca.mcgill.ecse211.threads.LightPoller" 3 "Thu Nov 29 2018" "Version 1.0" "ECSE211 - Fall 2018 - Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.threads.LightPoller
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBca\&.mcgill\&.ecse211\&.threads\&.ThreadControl\fP\&.
.PP
Inherited by \fBca\&.mcgill\&.ecse211\&.threads\&.RGBPoller\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLightPoller\fP (SampleProvider[] \fBus\fP, float[][] \fBlgData\fP, \fBSensorData\fP \fBcont\fP)  throws OdometerExceptions "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBrunMethod\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "SampleProvider \fBus\fP []"
.br
.ti -1c
.RI "\fBSensorData\fP \fBcont\fP"
.br
.ti -1c
.RI "float [][] \fBlgData\fP"
.br
.ti -1c
.RI "float \fBlastValue\fP []"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This class implements the Light Sensor Poller for our robot it runs pulls the sensor data every 50 miliseconds
.PP
\fBAuthor:\fP
.RS 4
Caspar Cedro 
.PP
Percy Chen 
.PP
Patrick Erath 
.PP
Anssam Ghezala 
.PP
Susan Matuszewski 
.PP
Kamy Moussavi Kafi 
.RE
.PP

.PP
Definition at line 17 of file LightPoller\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ca\&.mcgill\&.ecse211\&.threads\&.LightPoller\&.LightPoller (SampleProvider [] us, float lgData[][], \fBSensorData\fP cont) throws \fBOdometerExceptions\fP"
This constructor creates an instance of the \fBLightPoller\fP class to provide distance data from an light sensor to our robot\&.
.PP
\fBParameters:\fP
.RS 4
\fIus\fP A SampleProvider class instance that helps us to store an array of light sensor data\&. 
.br
\fIlgData\fP An array to store light sensor data\&. 
.br
\fIcont\fP A \fBSensorData\fP object instance to further store sensor data\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 33 of file LightPoller\&.java\&.
.PP
.nf
34                                 {
35     this\&.us = us;
36     this\&.cont = cont;
37     this\&.lgData = lgData;
38     isStarted = true;
39     lastValue = new float[2];
40     sensorNumber++;
41     WAIT_TIME = 50;
42   }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void ca\&.mcgill\&.ecse211\&.threads\&.LightPoller\&.runMethod ()\fC [protected]\fP"
This method reads light sensor data 
.PP
Definition at line 47 of file LightPoller\&.java\&.
.PP
.nf
47                              {
48     double l[] = new double[2];
49     for (int i = 0; i < us\&.length; i++) {
50       us[i]\&.fetchSample(lgData[i], 0); // acquire data
51 
52       int distance = (int) (lgData[i][0] * 100); // extract from buffer, multiply by 100 for
53                                                  // convenience
54       // and allow it to be cast to int
55       l[i] = distance - lastValue[i]; // now take action depending on value
56       lastValue[i] = distance;
57     }
58     cont\&.setL(l);
59   }
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBSensorData\fP ca\&.mcgill\&.ecse211\&.threads\&.LightPoller\&.cont\fC [protected]\fP"

.PP
Definition at line 19 of file LightPoller\&.java\&.
.SS "float ca\&.mcgill\&.ecse211\&.threads\&.LightPoller\&.lastValue[]\fC [protected]\fP"

.PP
Definition at line 21 of file LightPoller\&.java\&.
.SS "float [][] ca\&.mcgill\&.ecse211\&.threads\&.LightPoller\&.lgData\fC [protected]\fP"

.PP
Definition at line 20 of file LightPoller\&.java\&.
.SS "SampleProvider ca\&.mcgill\&.ecse211\&.threads\&.LightPoller\&.us[]\fC [protected]\fP"

.PP
Definition at line 18 of file LightPoller\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Final Project from the source code\&.
