.TH "ca.mcgill.ecse211.threads" 3 "Mon Nov 26 2018" "Version 1.0" "ECSE211 - Fall 2018 - Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.threads
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLightPoller\fP"
.br
.ti -1c
.RI "class \fBRGBPoller\fP"
.br
.ti -1c
.RI "class \fBSensorData\fP"
.br
.ti -1c
.RI "class \fBThreadControl\fP"
.br
.ti -1c
.RI "class \fBUltrasonicPoller\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Final Project from the source code\&.
