.TH "ca.mcgill.ecse211.project.WiFi" 3 "Fri Nov 2 2018" "Version 1.0" "ECSE211 - Fall 2018 - Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.project.WiFi
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWiFi\fP ()"
.br
.ti -1c
.RI "void \fBreadData\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class implements the ability to receive game parameters over \fBWiFi\fP
.PP
\fBAuthor:\fP
.RS 4
Caspar Cedro 
.PP
Percy Chen 
.PP
Patrick Erath 
.PP
Anssam Ghezala 
.PP
Susan Matuszewski 
.PP
Kamy Moussavi Kafi 
.RE
.PP

.PP
Definition at line 13 of file WiFi\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ca\&.mcgill\&.ecse211\&.project\&.WiFi\&.WiFi ()"
Constructs a \fBWiFi\fP class instance 
.PP
Definition at line 17 of file WiFi\&.java\&.
.PP
.nf
17                 {
18     
19   }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void ca\&.mcgill\&.ecse211\&.project\&.WiFi\&.readData ()"
(Not Implemented) read data from wifi 
.PP
Definition at line 24 of file WiFi\&.java\&.
.PP
.nf
24                          {
25     
26   }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Final Project from the source code\&.
