.TH "ca.mcgill.ecse211.project.GameParameters.AreaType" 3 "Thu Nov 8 2018" "Version 1.0" "ECSE211 - Fall 2018 - Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.project.GameParameters.AreaType
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBInStarting\fP"
.br
.ti -1c
.RI "\fBSearching\fP"
.br
.ti -1c
.RI "\fBDangerous\fP"
.br
.ti -1c
.RI "\fBStartingBoundary\fP"
.br
.ti -1c
.RI "\fBSearchingBoundary\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This enumeration contains the possible types of areas that our robot is currently located in 
.PP
Definition at line 19 of file GameParameters\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.AreaType\&.Dangerous"

.PP
Definition at line 20 of file GameParameters\&.java\&.
.SS "ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.AreaType\&.InStarting"

.PP
Definition at line 20 of file GameParameters\&.java\&.
.SS "ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.AreaType\&.Searching"

.PP
Definition at line 20 of file GameParameters\&.java\&.
.SS "ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.AreaType\&.SearchingBoundary"

.PP
Definition at line 20 of file GameParameters\&.java\&.
.SS "ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.AreaType\&.StartingBoundary"

.PP
Definition at line 20 of file GameParameters\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Final Project from the source code\&.
