.TH "ca.mcgill.ecse211" 3 "Fri Nov 2 2018" "Version 1.0" "ECSE211 - Fall 2018 - Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBlocalization\fP"
.br
.ti -1c
.RI "package \fBodometer\fP"
.br
.ti -1c
.RI "package \fBproject\fP"
.br
.ti -1c
.RI "package \fBtests\fP"
.br
.ti -1c
.RI "package \fBthreads\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Final Project from the source code\&.
