.TH "ca.mcgill.ecse211.tests.ComponentTest" 3 "Thu Nov 8 2018" "Version 1.0" "ECSE211 - Fall 2018 - Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.tests.ComponentTest
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBType\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBrunTest\fP (\fBType\fP testType)  throws Exception "
.br
.ti -1c
.RI "static void \fBnavigationTest\fP ()  throws OdometerExceptions "
.br
.ti -1c
.RI "static void \fBtunnelTest\fP ()  throws Exception "
.br
.ti -1c
.RI "static void \fBlocalizationTest\fP ()  throws OdometerExceptions "
.br
.ti -1c
.RI "static void \fBultrasonicSensorTest\fP ()"
.br
.ti -1c
.RI "static void \fBlightSensorTest\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This singleton contains all the methods and structures necessary to test our robot and its components
.PP
\fBAuthor:\fP
.RS 4
Caspar Cedro 
.PP
Percy Chen 
.PP
Patrick Erath 
.PP
Anssam Ghezala 
.PP
Susan Matuszewski 
.PP
Kamy Moussavi Kafi 
.RE
.PP

.PP
Definition at line 25 of file ComponentTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.lightSensorTest ()\fC [static]\fP"
Test for lightSensor 
.PP
Definition at line 118 of file ComponentTest\&.java\&.
.PP
.nf
118                                        {
119 
120   }
.fi
.SS "static void ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.localizationTest () throws \fBOdometerExceptions\fP\fC [static]\fP"
Test for localizationTest
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 92 of file ComponentTest\&.java\&.
.PP
.nf
92                                                                   {
93     Navigation navigation = new Navigation(Game\&.leftMotor, Game\&.rightMotor);
94     UltrasonicLocalizer us = new UltrasonicLocalizer(navigation, Game\&.leftMotor, Game\&.rightMotor);
95     LightLocalizer lgLoc = new LightLocalizer(navigation, Game\&.leftMotor, Game\&.rightMotor);
96     us\&.localize(Button\&.ID_LEFT);
97     lgLoc\&.localize(GameParameters\&.SC);
98     Game\&.INSTANCE\&.usPoller\&.setStart(false);
99     navigation\&.travelToWithCorrection(6, 4, false);
100     Sound\&.twoBeeps();
101     navigation\&.travelToWithCorrection(2, 3, false);
102     Sound\&.twoBeeps();
103     navigation\&.travelToWithCorrection(0, 0, false);
104     Game\&.INSTANCE\&.usPoller\&.setStart(true);
105 
106   }
.fi
.SS "static void ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.navigationTest () throws \fBOdometerExceptions\fP\fC [static]\fP"
Test for Navigation
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 70 of file ComponentTest\&.java\&.
.PP
.nf
70                                                                 {
71     Navigation nav = new Navigation(Game\&.leftMotor, Game\&.rightMotor);
72     nav\&.travelToWithCorrection(4, 2, false);
73     nav\&.travelToWithCorrection(0, 0, false);
74   }
.fi
.SS "static void ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.runTest (\fBType\fP testType) throws Exception\fC [static]\fP"
This method selects test for each individual components of the design
.PP
\fBParameters:\fP
.RS 4
\fItype\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 38 of file ComponentTest\&.java\&.
.PP
.nf
38                                                              {
39     try {
40       switch (testType) {
41         case Navigation:
42           ComponentTest\&.navigationTest();
43           break;
44         case Localization:
45           ComponentTest\&.localizationTest();
46           break;
47         case UltrasonicSensor:
48           ComponentTest\&.ultrasonicSensorTest();
49           break;
50         case LightSensor:
51           ComponentTest\&.lightSensorTest();
52           break;
53         case RingDetection:
54           //ComponentTest\&.ringMotorTest();
55           break;
56         default:
57           System\&.out\&.println("Invalid test type selected");
58           break;
59       }
60     } catch (Exception e) {
61       throw e;
62     }
63   }
.fi
.SS "static void ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.tunnelTest () throws Exception\fC [static]\fP"

.PP
Definition at line 76 of file ComponentTest\&.java\&.
.PP
.nf
76                                                    {
77     Navigation navigation = new Navigation(Game\&.leftMotor, Game\&.rightMotor);
78 
79     //UltrasonicLocalizer us = new UltrasonicLocalizer(navigation, Game\&.leftMotor, Game\&.rightMotor);
80     //LightLocalizer lgLoc = new LightLocalizer(navigation, Game\&.leftMotor, Game\&.rightMotor);
81     //us\&.localize(Button\&.ID_LEFT);
82     //lgLoc\&.localize(GameParameters\&.SC);
83     Odometer\&.getOdometer()\&.setXYT(1, 1, 0);
84     navigation\&.goThroughTunnel();
85   }
.fi
.SS "static void ca\&.mcgill\&.ecse211\&.tests\&.ComponentTest\&.ultrasonicSensorTest ()\fC [static]\fP"
Test for UltrasonicSensor 
.PP
Definition at line 111 of file ComponentTest\&.java\&.
.PP
.nf
111                                             {
112 
113   }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Final Project from the source code\&.
