.TH "ca.mcgill.ecse211.project.Game" 3 "Thu Oct 25 2018" "Version 1.0" "ECSE211 - Fall 2018 - Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.project.Game
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBpreparation\fP ()  throws OdometerExceptions "
.br
.ti -1c
.RI "static void \fBlocalization\fP ()"
.br
.ti -1c
.RI "static void \fBreadData\fP ()"
.br
.ti -1c
.RI "static void \fBrunGame\fP ()  throws OdometerExceptions "
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final EV3LargeRegulatedMotor \fBleftMotor\fP"
.br
.ti -1c
.RI "static final EV3LargeRegulatedMotor \fBrightMotor\fP"
.br
.ti -1c
.RI "static final double \fBTILE\fP = 30\&.48"
.br
.ti -1c
.RI "static final double \fBWHEEL_RAD\fP = 2\&.2"
.br
.ti -1c
.RI "static double \fBTRACK\fP = 10\&.3"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class implements the main starting point for the Search and Localize lab
.PP
\fBAuthor:\fP
.RS 4
Caspar Cedro 
.PP
Percy Chen 
.PP
Patrick Erath 
.PP
Anssam Ghezala 
.PP
Susan Matuszewski 
.PP
Kamy Moussavi Kafi 
.RE
.PP

.PP
Definition at line 33 of file Game\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ca\&.mcgill\&.ecse211\&.project\&.Game\&.localization ()\fC [static]\fP"
perform localization 
.PP
Definition at line 133 of file Game\&.java\&.
.SS "static void ca\&.mcgill\&.ecse211\&.project\&.Game\&.preparation () throws \fBOdometerExceptions\fP\fC [static]\fP"
Prepare for the game: starting thread, read all arguments
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 74 of file Game\&.java\&.
.SS "static void ca\&.mcgill\&.ecse211\&.project\&.Game\&.readData ()\fC [static]\fP"
Read data from the wifi class (using another thread) 
.PP
Definition at line 140 of file Game\&.java\&.
.SS "static void ca\&.mcgill\&.ecse211\&.project\&.Game\&.runGame () throws \fBOdometerExceptions\fP\fC [static]\fP"
This method contains main logic for the game plays
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 149 of file Game\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final EV3LargeRegulatedMotor ca\&.mcgill\&.ecse211\&.project\&.Game\&.leftMotor\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
      new EV3LargeRegulatedMotor(LocalEV3\&.get()\&.getPort("A"))
.fi
Motor object instance that allows control of the left motor connected to port B 
.PP
Definition at line 45 of file Game\&.java\&.
.SS "final EV3LargeRegulatedMotor ca\&.mcgill\&.ecse211\&.project\&.Game\&.rightMotor\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
      new EV3LargeRegulatedMotor(LocalEV3\&.get()\&.getPort("D"))
.fi
Motor object instance that allows control of the right motor connected to port A 
.PP
Definition at line 51 of file Game\&.java\&.
.SS "final double ca\&.mcgill\&.ecse211\&.project\&.Game\&.TILE = 30\&.48\fC [static]\fP"
length of the tile 
.PP
Definition at line 56 of file Game\&.java\&.
.SS "double ca\&.mcgill\&.ecse211\&.project\&.Game\&.TRACK = 10\&.3\fC [static]\fP"
This variable denotes the track distance between the center of the wheels in cm (measured and adjusted based on trial and error)\&. 
.PP
Definition at line 67 of file Game\&.java\&.
.SS "final double ca\&.mcgill\&.ecse211\&.project\&.Game\&.WHEEL_RAD = 2\&.2\fC [static]\fP"
This variable denotes the radius of our wheels in cm\&. 
.PP
Definition at line 61 of file Game\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Final Project from the source code\&.
