.TH "ca.mcgill.ecse211.localization.LightLocalizer" 3 "Thu Nov 8 2018" "Version 1.0" "ECSE211 - Fall 2018 - Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.localization.LightLocalizer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLightLocalizer\fP (\fBNavigation\fP nav, EV3LargeRegulatedMotor leftMotor, EV3LargeRegulatedMotor rightMotor)  throws OdometerExceptions "
.br
.ti -1c
.RI "void \fBlocalize\fP (int[] sC)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class helps our robot to localize itself using the light sensor
.PP
\fBAuthor:\fP
.RS 4
Caspar Cedro 
.PP
Percy Chen 
.PP
Patrick Erath 
.PP
Anssam Ghezala 
.PP
Susan Matuszewski 
.PP
Kamy Moussavi Kafi 
.RE
.PP

.PP
Definition at line 21 of file LightLocalizer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ca\&.mcgill\&.ecse211\&.localization\&.LightLocalizer\&.LightLocalizer (\fBNavigation\fP nav, EV3LargeRegulatedMotor leftMotor, EV3LargeRegulatedMotor rightMotor) throws \fBOdometerExceptions\fP"
This is the class constructor
.PP
\fBParameters:\fP
.RS 4
\fIleftMotor\fP 
.br
\fIrightMotor\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 38 of file LightLocalizer\&.java\&.
.PP
.nf
39                                                                    {
40     this\&.odometer = Odometer\&.getOdometer();
41     this\&.data = SensorData\&.getSensorData();
42     this\&.navigation = nav;
43     this\&.leftMotor = leftMotor;
44     this\&.rightMotor = rightMotor;
45   }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void ca\&.mcgill\&.ecse211\&.localization\&.LightLocalizer\&.localize (int [] sC)"
(\fIImprove\fP) Once the robot know what angle it is facing, this method looks for the x,y axis origins knowing it is in the first tile facing north\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsC\fP the coordinate to set to after localization 
.RE
.PP

.PP
Definition at line 53 of file LightLocalizer\&.java\&.
.PP
.nf
53                                  {
54     leftMotor\&.setSpeed(FORWARD_SPEED);
55     rightMotor\&.setSpeed(FORWARD_SPEED);
56 
57     // 1\&. GO forward find the y=0 line
58     leftMotor\&.forward();
59     rightMotor\&.forward();
60     while (leftMotor\&.isMoving() || rightMotor\&.isMoving()) {
61       if (data\&.getL()[0] < blackLineColor) {
62         leftMotor\&.stop(true);
63       }
64       if (data\&.getL()[1] < blackLineColor) {
65         rightMotor\&.stop(true);
66       }
67     }
68     odometer\&.setTheta(0\&.0);
69     Sound\&.beep();
70     odometer\&.setY(0);
71     // 2\&. Turn and go forward find the x=0 line
72     navigation\&.turnTo(90);
73     leftMotor\&.setSpeed(FORWARD_SPEED);
74     rightMotor\&.setSpeed(FORWARD_SPEED);
75     leftMotor\&.forward();
76     rightMotor\&.forward();
77     while (leftMotor\&.isMoving() || rightMotor\&.isMoving()) {
78       if (data\&.getL()[0] < blackLineColor) {
79         leftMotor\&.stop(true);
80       }
81       if (data\&.getL()[1] < blackLineColor) {
82         rightMotor\&.stop(true);
83       }
84     }
85     odometer\&.setTheta(90\&.0);
86     Sound\&.beep();
87     odometer\&.setX(0);
88     leftMotor\&.setSpeed(FORWARD_SPEED);
89     rightMotor\&.setSpeed(FORWARD_SPEED);
90     // 3\&. Go backwards by sensor-wheel center distance in x-direction
91     leftMotor\&.rotate(Navigation\&.convertDistance(Game\&.WHEEL_RAD, Game\&.SEN_DIS), true);
92     rightMotor\&.rotate(Navigation\&.convertDistance(Game\&.WHEEL_RAD, Game\&.SEN_DIS), false);
93     // 4\&. Go backwards by sensor-wheel center distance in y-direction
94     navigation\&.turnTo(0);
95     leftMotor\&.setSpeed(FORWARD_SPEED);
96     rightMotor\&.setSpeed(FORWARD_SPEED);
97     //double sensorDistanceOffset = 2\&.5;
98     leftMotor\&.rotate(
99         Navigation\&.convertDistance(Game\&.WHEEL_RAD, Game\&.SEN_DIS),
100         true);
101     rightMotor\&.rotate(
102         Navigation\&.convertDistance(Game\&.WHEEL_RAD, Game\&.SEN_DIS),
103         false);
104     odometer\&.setTheta(0);
105     odometer\&.setX(sC[0]);
106     odometer\&.setY(sC[1]);
107 
108   }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Final Project from the source code\&.
