.TH "ca.mcgill.ecse211.project.GameParameters.DemoType" 3 "Mon Nov 26 2018" "Version 1.0" "ECSE211 - Fall 2018 - Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.project.GameParameters.DemoType
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBeta\fP"
.br
.ti -1c
.RI "\fBFinal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This enumeration contains the type of demo that our robot is currently going to be performing in 
.PP
Definition at line 25 of file GameParameters\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.DemoType\&.Beta"

.PP
Definition at line 26 of file GameParameters\&.java\&.
.SS "ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.DemoType\&.Final"

.PP
Definition at line 26 of file GameParameters\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Final Project from the source code\&.
