.TH "ca.mcgill.ecse211.project.GameParameters" 3 "Thu Nov 29 2018" "Version 1.0" "ECSE211 - Fall 2018 - Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.project.GameParameters
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBAreaType\fP"
.br
.ti -1c
.RI "enum \fBDemoType\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBAreaType\fP \fBgetType\fP (int x, int y)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBAreaType\fP \fBArea\fP = \fBAreaType\&.InStarting\fP"
.br
.ti -1c
.RI "static \fBDemoType\fP \fBDemo\fP = \fBDemoType\&.Final\fP"
.br
.ti -1c
.RI "static int [] \fBSC\fP = {1, 7, 90}"
.br
.ti -1c
.RI "static int [] \fBSCUS\fP = {1, 1}"
.br
.ti -1c
.RI "static int [] \fBGrid_LL\fP = {0, 0}"
.br
.ti -1c
.RI "static int [] \fBGrid_UR\fP = {8, 8}"
.br
.ti -1c
.RI "static int \fBTargetRing\fP = \-1"
.br
.ti -1c
.RI "static int \fBPlayerTeamNumber\fP = 5"
.br
.ti -1c
.RI "static int \fBRedTeam\fP = \-1"
.br
.ti -1c
.RI "static int \fBGreenTeam\fP = \-1"
.br
.ti -1c
.RI "static int \fBUsCorner\fP = \-1"
.br
.ti -1c
.RI "static int \fBOCorner\fP = \-1"
.br
.ti -1c
.RI "static int [] \fBUS_LL\fP = {0, 0}"
.br
.ti -1c
.RI "static int [] \fBUS_UR\fP = {8, 8}"
.br
.ti -1c
.RI "static int [] \fBOPPO_LL\fP = {0, 5}"
.br
.ti -1c
.RI "static int [] \fBOPPO_UR\fP = {6, 8}"
.br
.ti -1c
.RI "static int [] \fBIsland_LL\fP = {4, 5}"
.br
.ti -1c
.RI "static int [] \fBIsland_UR\fP = {6, 8}"
.br
.ti -1c
.RI "static int [] \fBTN_LL\fP = {2, 6}"
.br
.ti -1c
.RI "static int [] \fBTN_UR\fP = {4, 7}"
.br
.ti -1c
.RI "static int [] \fBTNO_LL\fP = {10, 3}"
.br
.ti -1c
.RI "static int [] \fBTNO_UR\fP = {11, 5}"
.br
.ti -1c
.RI "static int [] \fBTREE_US\fP = {2, 2}"
.br
.ti -1c
.RI "static int [] \fBTTEE_O\fP = {13, 7}"
.br
.in -1c
.SH "Detailed Description"
.PP 
This singleton contains all the game parameters needed for the competition
.PP
\fBAuthor:\fP
.RS 4
Caspar Cedro 
.PP
Percy Chen 
.PP
Patrick Erath 
.PP
Anssam Ghezala 
.PP
Susan Matuszewski 
.PP
Kamy Moussavi Kafi 
.RE
.PP

.PP
Definition at line 13 of file GameParameters\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBAreaType\fP ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.getType (int x, int y)\fC [static]\fP"
This method decides the type of area a particular set of (x,y) coordinates belongs to
.PP
\fBParameters:\fP
.RS 4
\fIx\fP The x coordinate of the coordinate set 
.br
\fIy\fP The y coordinate of the coordinate set 
.RE
.PP
\fBReturns:\fP
.RS 4
The type of area the coordinates belong to 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 180 of file GameParameters\&.java\&.
.PP
.nf
180                                                {
181     if (x >= US_LL[0] && x <= US_UR[0] && y >= US_LL[1] && y <= US_UR[1]) {
182       return AreaType\&.InStarting;
183     }
184     if (x >= Island_LL[0] && x <= Island_UR[0] && y >= Island_LL[1] && y <= Island_UR[1]) {
185       return AreaType\&.Searching;
186     }
187 
188     return AreaType\&.Dangerous;
189   }
.fi
.SH "Member Data Documentation"
.PP 
.SS " static  \fBAreaType\fP ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.Area = \fBAreaType\&.InStarting\fP\fC [static]\fP"
This variable stores the current area that our robot is in during a competition 
.PP
Definition at line 33 of file GameParameters\&.java\&.
.SS " static  \fBDemoType\fP ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.Demo = \fBDemoType\&.Final\fP\fC [static]\fP"
This variable stores the current demo type that our robot is in during a competition 
.PP
Definition at line 38 of file GameParameters\&.java\&.
.SS " static  int ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.GreenTeam = \-1\fC [static]\fP"
This variable stores the team starting out from the green zone, possible values are [1,20] 
.PP
Definition at line 76 of file GameParameters\&.java\&.
.SS " static  int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.Grid_LL = {0, 0}\fC [static]\fP"
This variable stores the lower left coordinates of the entire grid 
.PP
Definition at line 49 of file GameParameters\&.java\&.
.SS " static  int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.Grid_UR = {8, 8}\fC [static]\fP"
This variable stores the upper right coordinates of the entire grid (8,8) for Beta Demo (15,9) for Final Demo 
.PP
Definition at line 55 of file GameParameters\&.java\&.
.SS " static  int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.Island_LL = {4, 5}\fC [static]\fP"
This variable stores the lower left hand corner of the island zone [0] = x coordinate, [1] = y coordinate min Island_UR[0] - Island_LL[0] = 2 max Island_UR[0] - Island_LL[0] = 10 min Island_UR[1] - Island_LL[1] = 2 max Island_UR[1] - Island_LL[1] = 10 
.PP
Definition at line 121 of file GameParameters\&.java\&.
.SS " static  int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.Island_UR = {6, 8}\fC [static]\fP"
This variable stores the upper right hand corner of the island zone [0] = x coordinate, [1] = y coordinate min Island_UR[0] - Island_LL[0] = 2 max Island_UR[0] - Island_LL[0] = 10 min Island_UR[1] - Island_LL[1] = 2 max Island_UR[1] - Island_LL[1] = 10 
.PP
Definition at line 128 of file GameParameters\&.java\&.
.SS " static  int ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.OCorner = \-1\fC [static]\fP"
This variable stores the starting corner for the green team, possible values are [0,3] 
.PP
Definition at line 86 of file GameParameters\&.java\&.
.SS " static  int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.OPPO_LL = {0, 5}\fC [static]\fP"
This variable stores the lower left hand corner of the green zone [0] = x coordinate, [1] = y coordinate min Green_UR[0] - Green_LL[0] = 2 max Green_UR[0] - Green_LL[0] = 10 min Green_UR[1]
.IP "\(bu" 2
Green_LL[1] = 2 max Green_UR[1] - Green_LL[1] = 10 
.PP

.PP
Definition at line 107 of file GameParameters\&.java\&.
.SS " static  int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.OPPO_UR = {6, 8}\fC [static]\fP"
This variable stores the upper right hand corner of the green zone [0] = x coordinate, [1] = y coordinate min Green_UR[0] - Green_LL[0] = 2 max Green_UR[0] - Green_LL[0] = 10 min Green_UR[1]
.IP "\(bu" 2
Green_LL[1] = 2 max Green_UR[1] - Green_LL[1] = 10 
.PP

.PP
Definition at line 114 of file GameParameters\&.java\&.
.SS " static  int ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.PlayerTeamNumber = 5\fC [static]\fP"
This variable stores the number of the team our robot is on 
.PP
Definition at line 66 of file GameParameters\&.java\&.
.SS " static  int ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.RedTeam = \-1\fC [static]\fP"
This variable stores the team starting out from the red zone, possible values are [1,20] 
.PP
Definition at line 71 of file GameParameters\&.java\&.
.SS " static  int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.SC = {1, 7, 90}\fC [static]\fP"
This variables holds the starting corner coordinates for our robot 
.PP
Definition at line 43 of file GameParameters\&.java\&.
.SS " static  int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.SCUS = {1, 1}\fC [static]\fP"

.PP
Definition at line 45 of file GameParameters\&.java\&.
.SS " static  int ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.TargetRing = \-1\fC [static]\fP"
This variable holds the color of the target ring in the range [1,4] 1 indicates a BLUE ring 2 indicates a GREEN ring 3 indicates a YELLOW ring 4 indicates an ORANGE ring 
.PP
Definition at line 61 of file GameParameters\&.java\&.
.SS " static  int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.TN_LL = {2, 6}\fC [static]\fP"
This variable stores the lower left hand corner of the red tunnel footprint [0] = x coordinate, [1] = y coordinate min BRR_UR[0] - BRR_LL[0] = 1 max BRR_UR[0] - BRR_LL[0] = 2 min BRR_UR[1] - BRR_LL[1] = 1 max BRR_UR[1] - BRR_LL[1] = 2 
.PP
Definition at line 135 of file GameParameters\&.java\&.
.SS " static  int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.TN_UR = {4, 7}\fC [static]\fP"
This variable stores the upper right hand corner of the red tunnel footprint [0] = x coordinate, [1] = y coordinate min BRR_UR[0] - BRR_LL[0] = 1 max BRR_UR[0] - BRR_LL[0] = 2 min BRR_UR[1] - BRR_LL[1] = 1 max BRR_UR[1] - BRR_LL[1] = 2 
.PP
Definition at line 142 of file GameParameters\&.java\&.
.SS " static  int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.TNO_LL = {10, 3}\fC [static]\fP"
This variable stores the lower left hand corner of the green tunnel footprint [0] = x coordinate, [1] = y coordinate min BRG_UR[0] - BRG_LL[0] = 1 max BRG_UR[0] - BRG_LL[0] = 2 min BRG_UR[1] - BRG_LL[1] = 1 max BRG_UR[1] - BRG_LL[1] = 2 
.PP
Definition at line 149 of file GameParameters\&.java\&.
.SS " static  int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.TNO_UR = {11, 5}\fC [static]\fP"
This variable stores the upper right hand corner of the green tunnel footprint [0] = x coordinate, [1] = y coordinate min BRG_UR[0] - BRG_LL[0] = 1 max BRG_UR[0] - BRG_LL[0] = 2 min BRG_UR[1] - BRG_LL[1] = 1 max BRG_UR[1] - BRG_LL[1] = 2 
.PP
Definition at line 156 of file GameParameters\&.java\&.
.SS " static  int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.TREE_US = {2, 2}\fC [static]\fP"
This variable stores the coordinates of the red player ring set [0] = x coordinate, [1] = y coordinate min TR_UR[0] - TR_LL[0] = 1 max TR_UR[0] - TR_LL[0] = 1 min TR_UR[1] - TR_LL[1] = 1 max TR_UR[1] - TR_LL[1] = 1 
.PP
Definition at line 163 of file GameParameters\&.java\&.
.SS " static  int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.TTEE_O = {13, 7}\fC [static]\fP"
This variable stores the coordinates of the green player ring set [0] = x coordinate, [1] = y coordinate min TG_UR[0] - TG_LL[0] = 1 max TG_UR[0] - TG_LL[0] = 1 min TG_UR[1] - TG_LL[1] = 1 max TG_UR[1] - TG_LL[1] = 1 
.PP
Definition at line 170 of file GameParameters\&.java\&.
.SS " static  int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.US_LL = {0, 0}\fC [static]\fP"
This variable stores the lower left hand corner of the red zone [0] = x coordinate, [1] = y coordinate min Red_UR[0] - Red_LL[0] = 2 max Red_UR[0] - Red_LL[0] = 10 min Red_UR[1] - Red_LL[1] = 2 max Red_UR[1] - Red_LL[1] = 10 
.PP
Definition at line 93 of file GameParameters\&.java\&.
.SS " static  int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.US_UR = {8, 8}\fC [static]\fP"
This variable stores the upper right hand corner of the red zone [0] = x coordinate, [1] = y coordinate min Red_UR[0] - Red_LL[0] = 2 max Red_UR[0] - Red_LL[0] = 10 min Red_UR[1] - Red_LL[1] = 2 max Red_UR[1] - Red_LL[1] = 10 
.PP
Definition at line 100 of file GameParameters\&.java\&.
.SS " static  int ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.UsCorner = \-1\fC [static]\fP"
This variable stores the starting corner for the red team, possible values are [0,3] 
.PP
Definition at line 81 of file GameParameters\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Final Project from the source code\&.
