.TH "ca.mcgill.ecse211.project.RingSearcher" 3 "Tue Nov 27 2018" "Version 1.0" "ECSE211 - Fall 2018 - Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.project.RingSearcher
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRingSearcher\fP (EV3LargeRegulatedMotor sensorMotor, EV3LargeRegulatedMotor rodMotor)  throws OdometerExceptions "
.br
.ti -1c
.RI "void \fBsearch\fP ()"
.br
.ti -1c
.RI "void \fBprepareSearch\fP ()"
.br
.ti -1c
.RI "void \fBresetSearch\fP ()"
.br
.ti -1c
.RI "void \fBprepareRetrieve\fP ()"
.br
.ti -1c
.RI "void \fBretrieveRing\fP ()"
.br
.ti -1c
.RI "void \fBresetRodMotor\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class helps our robot to search for rings on a grid itself as a thread will search and retrieve the rings
.PP
\fBAuthor:\fP
.RS 4
Caspar Cedro 
.PP
Percy Chen 
.PP
Patrick Erath 
.PP
Anssam Ghezala 
.PP
Susan Matuszewski 
.PP
Kamy Moussavi Kafi 
.RE
.PP

.PP
Definition at line 21 of file RingSearcher\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ca\&.mcgill\&.ecse211\&.project\&.RingSearcher\&.RingSearcher (EV3LargeRegulatedMotor sensorMotor, EV3LargeRegulatedMotor rodMotor) throws \fBOdometerExceptions\fP"
This class provides method to check if there is a ring and if the ring is the color we want
.PP
\fBParameters:\fP
.RS 4
\fIstoragenMotor\fP the motor to move the storage of the robot 
.br
\fIrodMotor\fP the motor for the rod to collect the ring 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 42 of file RingSearcher\&.java\&.
.PP
.nf
43                                 {
44     this\&.odometer = Odometer\&.getOdometer();
45     this\&.sensorMotor = sensorMotor;
46     this\&.rodMotor = rodMotor;
47     rodMotor\&.setSpeed(ROD_SPEED);
48     this\&.sensorMotor\&.setSpeed(SENSOR_SPEED);
49     data = SensorData\&.getSensorData();
50     for (BaseRegulatedMotor motor : new BaseRegulatedMotor[] {this\&.sensorMotor, this\&.rodMotor}) {
51       motor\&.stop();
52       motor\&.setAcceleration(ACCELERATION);
53     }
54   }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void ca\&.mcgill\&.ecse211\&.project\&.RingSearcher\&.prepareRetrieve ()"
This method rotate the rod to a suitable position for retrieve the ring 
.PP
Definition at line 111 of file RingSearcher\&.java\&.
.PP
.nf
111                                 {
112     rodMotor\&.rotate(ROD_PREPARE);
113   }
.fi
.SS "void ca\&.mcgill\&.ecse211\&.project\&.RingSearcher\&.prepareSearch ()"
This method put the sensor to search rotation to be ready for the searching 
.PP
Definition at line 97 of file RingSearcher\&.java\&.
.PP
.nf
97                               {
98     sensorMotor\&.rotate(SENSOR_ROTATION);
99   }
.fi
.SS "void ca\&.mcgill\&.ecse211\&.project\&.RingSearcher\&.resetRodMotor ()"
Rotate the rod back to the original position 
.PP
Definition at line 125 of file RingSearcher\&.java\&.
.PP
.nf
125                               {
126     rodMotor\&.rotate(-(ROD_PREPARE + ROD_RETRIEVE));
127   }
.fi
.SS "void ca\&.mcgill\&.ecse211\&.project\&.RingSearcher\&.resetSearch ()"
This method put the sensor back 
.PP
Definition at line 104 of file RingSearcher\&.java\&.
.PP
.nf
104                             {
105     sensorMotor\&.rotateTo(0);
106   }
.fi
.SS "void ca\&.mcgill\&.ecse211\&.project\&.RingSearcher\&.retrieveRing ()"
this method retrieve the searched ring 
.PP
Definition at line 118 of file RingSearcher\&.java\&.
.PP
.nf
118                              {
119     rodMotor\&.rotate(ROD_RETRIEVE);
120   }
.fi
.SS "void ca\&.mcgill\&.ecse211\&.project\&.RingSearcher\&.search ()"
This method searches for the ring and identify its color based using the rod, It will beep based on the color of the ring 
.PP
Definition at line 61 of file RingSearcher\&.java\&.
.PP
.nf
61                        {
62     sensorMotor\&.rotate(SENSOR_ROTATION);
63     sensorMotor\&.rotate(-SENSOR_ROTATION);
64 
65     // determine most frequent colour detected and beep accordingly
66     Game\&.INSTANCE\&.rgbPoller\&.setStart(false);
67     switch (ColorCalibrator\&.getMostFrequenct()) {
68       case Orange:
69         Sound\&.beep();
70         Sound\&.beep();
71         Sound\&.beep();
72         Sound\&.beep();
73         break;
74       case Yellow:
75         Sound\&.beep();
76         Sound\&.beep();
77         Sound\&.beep();
78         break;
79       case Green:
80         Sound\&.beep();
81         Sound\&.beep();
82         break;
83       case Blue:
84         Sound\&.beep();
85         break;
86       case Other:
87         break;
88       default:
89         break;
90     }
91     Game\&.INSTANCE\&.rgbPoller\&.setStart(true);
92   }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Final Project from the source code\&.
