.TH "ca.mcgill.ecse211.localization.UltrasonicLocalizer" 3 "Thu Nov 8 2018" "Version 1.0" "ECSE211 - Fall 2018 - Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.localization.UltrasonicLocalizer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUltrasonicLocalizer\fP (\fBNavigation\fP nav, EV3LargeRegulatedMotor leftMotor, EV3LargeRegulatedMotor rightMotor)  throws OdometerExceptions "
.br
.ti -1c
.RI "void \fBlocalize\fP (int buttonChoice)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class helps our robot to localize itself using the ultrasonic sensor
.PP
\fBAuthor:\fP
.RS 4
Caspar Cedro 
.PP
Percy Chen 
.PP
Patrick Erath 
.PP
Anssam Ghezala 
.PP
Susan Matuszewski 
.PP
Kamy Moussavi Kafi 
.RE
.PP

.PP
Definition at line 21 of file UltrasonicLocalizer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ca\&.mcgill\&.ecse211\&.localization\&.UltrasonicLocalizer\&.UltrasonicLocalizer (\fBNavigation\fP nav, EV3LargeRegulatedMotor leftMotor, EV3LargeRegulatedMotor rightMotor) throws \fBOdometerExceptions\fP"
This is the class constructor for a class that helps to localize our robot with an ultrasonic sensor
.PP
\fBParameters:\fP
.RS 4
\fIleftMotor\fP A EV3LargeRegularedMotor object instance that allows control of the left motor 
.br
\fIrightMotor\fP A EV3LargeRegularedMotor object instance that allows control of the right motor 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 43 of file UltrasonicLocalizer\&.java\&.
.PP
.nf
44                                                                    {
45     this\&.odometer = Odometer\&.getOdometer();
46     this\&.data = SensorData\&.getSensorData();
47     this\&.navigation = nav;
48     this\&.leftMotor = leftMotor;
49     this\&.rightMotor = rightMotor;
50   }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void ca\&.mcgill\&.ecse211\&.localization\&.UltrasonicLocalizer\&.localize (int buttonChoice)"
Wrapper for risingEdge or falling edge methods\&. Left or Right button option\&.
.PP
\fBParameters:\fP
.RS 4
\fIbuttonChoice\fP The left or right button on the EV3 brick 
.RE
.PP

.PP
Definition at line 57 of file UltrasonicLocalizer\&.java\&.
.PP
.nf
57                                          {
58     if (buttonChoice == Button\&.ID_RIGHT) {
59       risingEdge();
60     } else {
61       fallingEdge();
62     }
63   }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Final Project from the source code\&.
