.TH "ca.mcgill" 3 "Thu Nov 29 2018" "Version 1.0" "ECSE211 - Fall 2018 - Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBecse211\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Final Project from the source code\&.
