.TH "ca.mcgill.ecse211.project.GameParameters" 3 "Fri Nov 2 2018" "Version 1.0" "ECSE211 - Fall 2018 - Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.project.GameParameters
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBAreaType\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBAreaType\fP \fBgetType\fP (double x, double y)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int [] \fBSC\fP = {\-1, \-1}"
.br
.ti -1c
.RI "static int [] \fBGrid_LL\fP = {0, 0}"
.br
.ti -1c
.RI "static int [] \fBGrid_UR\fP = {15, 9}"
.br
.ti -1c
.RI "static int \fBTR\fP = \-1"
.br
.ti -1c
.RI "static int \fBPlayerTeamNumber\fP = \-1"
.br
.ti -1c
.RI "static int \fBRedTeam\fP = \-1"
.br
.ti -1c
.RI "static int \fBGreenTeam\fP = \-1"
.br
.ti -1c
.RI "static int \fBRedCorner\fP = \-1"
.br
.ti -1c
.RI "static int \fBGreenCorner\fP = \-1"
.br
.ti -1c
.RI "static int [] \fBRed_LL\fP = {0, 5}"
.br
.ti -1c
.RI "static int [] \fBRed_UR\fP = {4, 9}"
.br
.ti -1c
.RI "static int [] \fBGreen_LL\fP = {10, 0}"
.br
.ti -1c
.RI "static int [] \fBGreen_UR\fP = {15, 4}"
.br
.ti -1c
.RI "static int [] \fBBRR_LL\fP = {4, 7}"
.br
.ti -1c
.RI "static int [] \fBBRR_UR\fP = {6, 8}"
.br
.ti -1c
.RI "static int [] \fBBRG_LL\fP = {10, 3}"
.br
.ti -1c
.RI "static int [] \fBBRG_UR\fP = {11, 5}"
.br
.ti -1c
.RI "static int [] \fBTR_LL\fP = {7, 6}"
.br
.ti -1c
.RI "static int [] \fBTR_UR\fP = {8, 7}"
.br
.ti -1c
.RI "static int [] \fBTG_LL\fP = {13, 7}"
.br
.ti -1c
.RI "static int [] \fBTG_UR\fP = {14, 8}"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class contains all the game parameters needed for the competition
.PP
\fBAuthor:\fP
.RS 4
Caspar Cedro 
.PP
Percy Chen 
.PP
Patrick Erath 
.PP
Anssam Ghezala 
.PP
Susan Matuszewski 
.PP
Kamy Moussavi Kafi 
.RE
.PP

.PP
Definition at line 13 of file GameParameters\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBAreaType\fP ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.getType (double x, double y)\fC [static]\fP"
Giving a coordinate, find the type of area it belongs to 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP x coordinate 
.br
\fIy\fP y coordinate 
.RE
.PP
\fBReturns:\fP
.RS 4
: the type of area the point belongs to 
.RE
.PP

.PP
Definition at line 200 of file GameParameters\&.java\&.
.PP
.nf
200                                                      {
201     return AreaType\&.Searching;
202   }
.fi
.SH "Member Data Documentation"
.PP 
.SS "int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.BRG_LL = {10, 3}\fC [static]\fP"
This variable stores the lower left hand corner of the green tunnel footprint\&. [0] = x coordinate, [1] = y coordinate min BRG_UR[0] - BRG_LL[0] = 1 max BRG_UR[0] - BRG_LL[0] = 2 min BRG_UR[1] - BRG_LL[1] = 1 max BRG_UR[1] - BRG_LL[1] = 2 
.PP
Definition at line 142 of file GameParameters\&.java\&.
.SS "int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.BRG_UR = {11, 5}\fC [static]\fP"
This variable stores the upper right hand corner of the green tunnel footprint\&. [0] = x coordinate, [1] = y coordinate min BRG_UR[0] - BRG_LL[0] = 1 max BRG_UR[0] - BRG_LL[0] = 2 min BRG_UR[1] - BRG_LL[1] = 1 max BRG_UR[1] - BRG_LL[1] = 2 
.PP
Definition at line 152 of file GameParameters\&.java\&.
.SS "int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.BRR_LL = {4, 7}\fC [static]\fP"
This variable stores the lower left hand corner of the red tunnel footprint\&. [0] = x coordinate, [1] = y coordinate min BRR_UR[0] - BRR_LL[0] = 1 max BRR_UR[0] - BRR_LL[0] = 2 min BRR_UR[1] - BRR_LL[1] = 1 max BRR_UR[1] - BRR_LL[1] = 2 
.PP
Definition at line 122 of file GameParameters\&.java\&.
.SS "int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.BRR_UR = {6, 8}\fC [static]\fP"
This variable stores the upper right hand corner of the red tunnel footprint\&. [0] = x coordinate, [1] = y coordinate min BRR_UR[0] - BRR_LL[0] = 1 max BRR_UR[0] - BRR_LL[0] = 2 min BRR_UR[1] - BRR_LL[1] = 1 max BRR_UR[1] - BRR_LL[1] = 2 
.PP
Definition at line 132 of file GameParameters\&.java\&.
.SS "int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.Green_LL = {10, 0}\fC [static]\fP"
This variable stores the lower left hand corner of the green zone\&. [0] = x coordinate, [1] = y coordinate min Green_UR[0] - Green_LL[0] = 2 max Green_UR[0] - Green_LL[0] = 10 min Green_UR[1] - Green_LL[1] = 2 max Green_UR[1] - Green_LL[1] = 10 
.PP
Definition at line 102 of file GameParameters\&.java\&.
.SS "int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.Green_UR = {15, 4}\fC [static]\fP"
This variable stores the upper right hand corner of the green zone\&. [0] = x coordinate, [1] = y coordinate min Green_UR[0] - Green_LL[0] = 2 max Green_UR[0] - Green_LL[0] = 10 min Green_UR[1] - Green_LL[1] = 2 max Green_UR[1] - Green_LL[1] = 10 
.PP
Definition at line 112 of file GameParameters\&.java\&.
.SS "int ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.GreenCorner = \-1\fC [static]\fP"
This variable stores the starting corner for the green team, possible values are [0,3]\&. 
.PP
Definition at line 72 of file GameParameters\&.java\&.
.SS "int ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.GreenTeam = \-1\fC [static]\fP"
This variable stores the team starting out from the green zone, possible values are [1,20]\&. 
.PP
Definition at line 62 of file GameParameters\&.java\&.
.SS "int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.Grid_LL = {0, 0}\fC [static]\fP"
This variable stores the lower left coordinates of the entire grid\&. 
.PP
Definition at line 36 of file GameParameters\&.java\&.
.SS "int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.Grid_UR = {15, 9}\fC [static]\fP"
This variable stores the upper right coordinates of the entire grid\&. 
.PP
Definition at line 41 of file GameParameters\&.java\&.
.SS "int ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.PlayerTeamNumber = \-1\fC [static]\fP"
This variable stores the number of the team our robot is on\&. 
.PP
Definition at line 52 of file GameParameters\&.java\&.
.SS "int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.Red_LL = {0, 5}\fC [static]\fP"
This variable stores the lower left hand corner of the red zone\&. [0] = x coordinate, [1] = y coordinate min Red_UR[0] - Red_LL[0] = 2 max Red_UR[0] - Red_LL[0] = 10 min Red_UR[1] - Red_LL[1] = 2 max Red_UR[1] - Red_LL[1] = 10 
.PP
Definition at line 82 of file GameParameters\&.java\&.
.SS "int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.Red_UR = {4, 9}\fC [static]\fP"
This variable stores the upper right hand corner of the red zone\&. [0] = x coordinate, [1] = y coordinate min Red_UR[0] - Red_LL[0] = 2 max Red_UR[0] - Red_LL[0] = 10 min Red_UR[1] - Red_LL[1] = 2 max Red_UR[1] - Red_LL[1] = 10 
.PP
Definition at line 92 of file GameParameters\&.java\&.
.SS "int ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.RedCorner = \-1\fC [static]\fP"
This variable stores the starting corner for the red team, possible values are [0,3]\&. 
.PP
Definition at line 67 of file GameParameters\&.java\&.
.SS "int ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.RedTeam = \-1\fC [static]\fP"
This variable stores the team starting out from the red zone, possible values are [1,20]\&. 
.PP
Definition at line 57 of file GameParameters\&.java\&.
.SS "int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.SC = {\-1, \-1}\fC [static]\fP"
This variables holds the starting corner coordinates for our robot\&. 
.PP
Definition at line 31 of file GameParameters\&.java\&.
.SS "int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.TG_LL = {13, 7}\fC [static]\fP"
This variable stores the lower left hand corner of the green player ring set\&. [0] = x coordinate, [1] = y coordinate min TG_UR[0] - TG_LL[0] = 1 max TG_UR[0] - TG_LL[0] = 1 min TG_UR[1] - TG_LL[1] = 1 max TG_UR[1] - TG_LL[1] = 1 
.PP
Definition at line 182 of file GameParameters\&.java\&.
.SS "int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.TG_UR = {14, 8}\fC [static]\fP"
This variable stores the upper right hand corner of the green player ring set\&. [0] = x coordinate, [1] = y coordinate min TG_UR[0] - TG_LL[0] = 1 max TG_UR[0] - TG_LL[0] = 1 min TG_UR[1] - TG_LL[1] = 1 max TG_UR[1] - TG_LL[1] = 1 
.PP
Definition at line 192 of file GameParameters\&.java\&.
.SS "int ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.TR = \-1\fC [static]\fP"
This variable holds the color of the target ring in the range [1,4]\&. 1 indicates a BLUE ring 2 indicates a GREEN ring 3 indicates a YELLOW ring 4 indicates an ORANGE ring 
.PP
Definition at line 47 of file GameParameters\&.java\&.
.SS "int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.TR_LL = {7, 6}\fC [static]\fP"
This variable stores the lower left hand corner of the red player ring set\&. [0] = x coordinate, [1] = y coordinate min TR_UR[0] - TR_LL[0] = 1 max TR_UR[0] - TR_LL[0] = 1 min TR_UR[1] - TR_LL[1] = 1 max TR_UR[1] - TR_LL[1] = 1 
.PP
Definition at line 162 of file GameParameters\&.java\&.
.SS "int [] ca\&.mcgill\&.ecse211\&.project\&.GameParameters\&.TR_UR = {8, 7}\fC [static]\fP"
This variable stores the upper right hand corner of the red player ring set\&. [0] = x coordinate, [1] = y coordinate min TR_UR[0] - TR_LL[0] = 1 max TR_UR[0] - TR_LL[0] = 1 min TR_UR[1] - TR_LL[1] = 1 max TR_UR[1] - TR_LL[1] = 1 
.PP
Definition at line 172 of file GameParameters\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Final Project from the source code\&.
